### ISSUE TITLE
Global/application rate limits applied twice if per route rate limits are also specified

### ISSUE THREAD

**Issue by tkrajca** [alisaifee/flask-limiter#108]
I believe that when application rate limits are specified and a per endpoint rate limit is specified, then the application rate limits are applied twice - once in the before_request() hook and second in the decorated route, i.e. one request is counted as if it was 2.

Example:
```python
app = Flask(__name__)
limiter = Limiter(app, application_limits=["600 per minute"])

@app.route("/")
@limiter.limit("300 per minute")
def index():
    return "test"

@app.route("/2")
def index2():
    return "test2"
```
Every request to / will be counted as two requests towards the application limit of 600 per minute and as one request towards the per route limit of 300 per minute.

With /2, everything works as expected in that one request counts as one request towards the application limit of 600 per minute.

Looking at the code, I think this is handled for default_limits but not for application_limits. I might be able to have a go at a patch but not sure when.

**Comment by alisaifee** [comment]
Sorry for the delay in getting this out - it has been fixed and released in `1.0.1`
