### ISSUE TITLE
Rate Limiting On 404 Pages

### ISSUE THREAD

**Issue by michaelm244** [alisaifee/flask-limiter#109]
I'd like to rate limit on routes including 404 pages, is there a way to do this? I've been trying things out from the docs but nothing works.

It seems that the standard `Limiter(app, key_func=blah, application_limits=["2 per hour"])` rate limits all Flask routes, but not on error handlers like 404 pages.

Is there an option to enable this?

**Comment by lukas-gitl** [comment]
Just write a custom handler and decorate it.

**Comment by alisaifee** [comment]
Closing as I assume the suggested approach worked :)

**Comment by zoltan-fedor** [comment]
I have tried exactly that "write a custom handler and decorate it" - but rate limiting is not triggered on error handlers, but being silently ignored:

This doesn't work:
```
@api.app_errorhandler(404)
@limiter.limit('1/hour')
def page_not_found(e):
    return make_response(jsonify(error=f"Page doesn't exist: {e.description}"), 404)
```

While this does (to prove that rate limiting is on in the given blueprint):
```
@api.route('/test/', methods=['GET'])
@limiter.limit('1/hour')
def test():
    return 'test'
```
