### ISSUE TITLE
Is the rate limiting done per user (cookie), per IP address, or another method?

### ISSUE THREAD

**Issue by josephernest** [alisaifee/flask-limiter#118]
Thanks for flask-limiter.
Is the rate limiting done per user (cookie), per IP address, or another method?
(it might be interesting to mention it in README).
All the best

**Comment by alisaifee** [comment]
Hi @josephernest - there is no default method and it's up to you to decide. In earlier versions, there was a naiive default of using the ip address of the request, but this has been deprecated (though you can still use the utility methods available). More information about this here: [rate limiting domain docs](https://flask-limiter.readthedocs.io/en/stable/#rate-limit-domain)
