### ISSUE TITLE
'KeyError' with high load

### ISSUE THREAD

**Issue by RetardVeverca** [alisaifee/flask-limiter#130]
Flask limiter is getting exceptions with 'KeyError' when 300-500 requests/s hit the server as a result connections are getting dropped and latency on the server spikes out to 30sec+.

Exception:

`
Exception in thread Thread-1243:
[Fri Mar 16 17:59:56.230903 2018] [:error] [pid 16263] Traceback (most recent call last):
[Fri Mar 16 17:59:56.230920 2018] [:error] [pid 16263]   File "/usr/lib64/python2.7/threading.py", line 804, in __bootstrap_inner
[Fri Mar 16 17:59:56.232584 2018] [:error] [pid 16263]     self.run()
[Fri Mar 16 17:59:56.234322 2018] [:error] [pid 16263]   File "/usr/lib64/python2.7/threading.py", line 1076, in run
[Fri Mar 16 17:59:56.234341 2018] [:error] [pid 16263]     self.function(*self.args, **self.kwargs)
[Fri Mar 16 17:59:56.237711 2018] [:error] [pid 16263]   File "/opt/python/run/venv/lib/python2.7/site-packages/limits/storage.py", line 135, in __expire_events
[Fri Mar 16 17:59:56.265323 2018] [:error] [pid 16263]     if self.expirations[key] <= time.time():
[Fri Mar 16 17:59:56.267128 2018] [:error] [pid 16263] KeyError: 'LIMITER/85.10.51.12/get_user_data/60/1/minute'
`

Config: 
`
limiter = Limiter(
    application,
    key_func=get_ipaddr,
    default_limits=["200/hour", "60/minute"]
)
`
With some routes having additional:
`
@limiter.limit("30/minute")
`

Server: 8 vCPU, 32 GB RAM, 64bit Amazon Linux 2017.03 v2.5.1 running Python 2.7, Apache 2.4.27 with mod_wsgi 3.5

Any idea what is going on?

Thank you!

**Comment by simlu** [comment]
What storage do you use? Could this be a problem with memcache size?

**Comment by RetardVeverca** [comment]
Default one - so normal memory. There is more than 20GB of memory available on the instance when these exceptions occur.

**Comment by simlu** [comment]
@RetardVeverca Separate from this issue: I'm assuming you are using multiple threads. This will mean that limits are not working as expected. With the memory storage the limits are not shared between threads. Effectively this means that the limits are much higher than what you configure. I would recommend switching to memcache or reddis, which is what most people use in production.

I'm not sure what went wrong in your particular case, maybe @alisaifee can look into it!
