### ISSUE TITLE
Typos in links to resolved GitHub issues in changelog

### ISSUE THREAD

**Issue by slint** [alisaifee/flask-limiter#133]
The link to the resolved issues in the changelogs have a small typo (thus resolving to a 404 page). Example in [1.0.0 2017-11-06](http://flask-limiter.readthedocs.io/en/stable/#id4):

> https://github.com/alisiafee/flask-limiter/issues/41

`s/alisiafee/alisaifee`

**Comment by alisaifee** [comment]
Fixed by c0eb703b3b01dd399c9c5e618a14700d376cc4b7
