### ISSUE TITLE
Unit tests do not result in 429 error.

### ISSUE THREAD

**Issue by adyouri** [alisaifee/flask-limiter#147]
Hi, I am having a difficult time testing Flask-Limiter rate limits.
I am using `pytest` and the [`pytest-flask`](http://pytest-flask.readthedocs.io/) plugin, but I also tried it with the built-in `unittest` module and it still fails.

I built a simple application to demonstrate the problem.

## `routes.py`:

```
from flask import Flask
from flask_limiter import Limiter
from flask_limiter.util import get_remote_address

app = Flask(__name__)
limiter = Limiter(app, key_func=get_remote_address)

@app.route('/test')
@limiter.limit('2 per day')
def test():
    return '42'

```

## `conftest.py`:

```
import pytest

from routes import app as application

@pytest.fixture
def app():
    return application

```

## `tests.py`:

```
import pytest
from flask import url_for

def test_flask_limiter(client):
    for i in range(3): # the limit is 2 per day
        res = client.get(url_for('test'))
    assert res.status_code == 429
```

Running `pytest tests.py` always fails with the status code being 200 instead of 429.

Using the flask test_client in the python repl gives the expected result:

```
>>> from routes import app
>>> client = app.test_client()
>>> client.get('/test')
<Response streamed [200 OK]>
>>> client.get('/test')
<Response streamed [200 OK]>
>>> client.get('/test')
<Response streamed [429 TOO MANY REQUESTS]>
```

Here is the `unittest` test (which also fails):

```
import unittest

from routes import app

class TestFlaskLimiter(unittest.TestCase):
    def test_flask_limiter(self):
        client = app.test_client()
        ctx = app.test_request_context()
        ctx.push()
        for i in range(3):
            res = client.get('/test')
        assert res.status_code == 429
if __name__ == '__main__':
    unittest.main()
```

**Comment by skion** [comment]
I also ran into this and it appears to have to do with whether or not `app.test_request_context()` is activated.

```
from flask import Flask
from flask_limiter import Limiter
from flask_limiter.util import get_remote_address

app = Flask(__name__)
limiter = Limiter(app, key_func=get_remote_address, strategy="fixed-window")


@app.route('/test')
@limiter.limit('2 per day')
def test():
    return '42'


if __name__ == "__main__":
    client = app.test_client()
    with app.app_context():
        for i in range(20):  # the limit is 2 per day
            res = client.get("/test")
    assert res.status_code == 429, "not rate limited"
```

Remove the context to make above work...

**Comment by Dutchy-** [comment]
I'm trying to do the same with pytest-flask and I've encountered the same problem. The logging shows that the key function is called only once, even though I do multiple requests. A real world scenario would call it for each request. I think the test client somehow re-uses the request... I have not been able to make this work in a unittest.

**Comment by Dutchy-** [comment]
I have been able to make this work by ignoring the pytest-flask created app altogether and instantiating my own:

```
local_app: Flask = app()
client = local_app.test_client()

data={}
ratelimit = 10
for i in range(ratelimit * 2):
    client.post('/my_endpoint', json=data)

res: Response = client.post('/my_endpoint', json=data)
assert res.status_code == 429
```

**Comment by skion** [comment]
The problem isn't there in 0.9.5.1, which I'm therefore pinning to at the moment.

A quick bisect points to PR #100 introducing it.

**Comment by Dutchy-** [comment]
One more thing I can add is that with my workaround example, the next unit test which uses the same app instance will have its requests fail immediately due to the rate limiter. For that reason, in my app fixture, I explicitly reload my api module which contains my app (`api.app`) using:

```
importlib.reload(api)
```

**Comment by activeperception** [comment]
I've had the same issue and, after a bit of debugging, I found that the issue is with a flask-limiter optimization that clashes with the test client. 

The solution for me was to call
`            g._rate_limiting_complete = False`
after every client.post.

I hope it helps, 
Raffaele

**Comment by rciorba** [comment]
> I've had the same issue and, after a bit of debugging, I found that the issue is with a flask-limiter optimization that clashes with the test client.
> 
> The solution for me was to call
> ` g._rate_limiting_complete = False`
> after every client.post.
> 
> I hope it helps,
> Raffaele

I think this is because of this design choice in flask: https://github.com/pallets/flask/issues/2567
Basically the if you have multiple requests with the test_client they all share one app_context and the same g.

**Comment by mbtronics** [comment]
Since this commit [2398d6903ee02c208527c3de37419eec90eff2eb](https://github.com/alisaifee/flask-limiter/commit/2398d6903ee02c208527c3de37419eec90eff2eb), the solution above does not work anymore.

Try this:
`setattr(g, '%s_rate_limiting_complete' % limiter._key_prefix, False)`
