### ISSUE TITLE
Support for twem-proxy.

### ISSUE THREAD

**Issue by breerly** [alisaifee/flask-limiter#18]
Wondering what it would take to simplify the `RedisStorage` adapter to avoid methods twemproxy doesn't support  - (lock, pipeline, script load, etc). Those looking to solve a high availability story will no doubt want to employ twemproxy for redis replication.

https://github.com/alisaifee/flask-limiter/blob/master/flask_limiter/storage.py#L268

Thoughts?

**Comment by alisaifee** [comment]
``RedisStorage`` refactored in 0dd94b2bdb15389ccae337934abc802cfd3e21d6 and released in ``0.7``
