### ISSUE TITLE
How to reset counter for a single key?

### ISSUE THREAD

**Issue by sliwinski-milosz** [alisaifee/flask-limiter#189]
Lets say that I limit requests based on IP.
```
flask-limiter: WARNING: ratelimit 100 per 1 month (127.0.0.1) exceeded at endpoint:
```
Now I want to unblock `127.0.0.1` IP but I don't want to reset counter for other IP's.

Is there a way to reset counter for a single key?

**Comment by CheeseTheMonkey** [comment]
You could use the `exempt_when` keyword? see https://flask-limiter.readthedocs.io/en/stable/#decorators

Something like:
`@limiter.limit('100/month', exempt_when=lambda: flask_limiter.util.ip_addr() == '127.0.0.1')`

**Comment by sliwinski-milosz** [comment]
Yeah, that is one option but it is more useful for static keys and for disabling limits at all for those keys.

I was thinking more about the case when I don't know the key beforehand:
Lets say that instead of limiting on IP, I limit based on api_key that client uses.
Because of the bug on the client side he got blocked. I'd like to reset counter for him. At the same time I don't want to completely disable limiting for him - so if extensive usage occurs, he will get blocked again.

I am looking for the way to reset counter in some edge cases that may occur in time without having to reset limits for everyone.

**Comment by nicolaspanel** [comment]
> I am looking for the way to reset counter in some edge cases that may occur in time without having to reset limits for everyone.

@sliwinski-milosz Have you found a workaround to do that ?

**Comment by sliwinski-milosz** [comment]
No :) You can connect directly to the storage and remove it from there.

**Comment by nicolaspanel** [comment]
thanks @sliwinski-milosz  for the answer !
I end up with
```py
        storage = self.limiter.storage()
        for key in storage.storage.keys('LIMITER/{}/*'.format(limit_key)):
            storage.storage.delete(key)
```

**Comment by Sheshtawy** [comment]
Another work around is to use the underlying `limits` API:  [`clear()`](https://limits.readthedocs.io/en/stable/api.html#limits.storage.Storage.clear)

Anyways, I think this would be a very helpful feature to have.

**Comment by VasundharaKumar2020** [comment]
@nicolaspanel Thanks that answer helps, how do you get the limit_key? appreciate your input

**Comment by HypertextAssassin0273** [comment]
> [@nicolaspanel](https://github.com/nicolaspanel) Thanks that answer helps, how do you get the limit_key? appreciate your input

u can use get_remote_address() [from flask_limiter.util] or request.remote_addr
