### ISSUE TITLE
Rate limiting a route without decorator

### ISSUE THREAD

**Issue by dmwesterhoff** [alisaifee/flask-limiter#195]
Is there a way to do inline rate limiting, I have a design constraint due to a custom framework that doesn't allow for me to use the `limit` decorator.

example of what I am trying to do:

```
@route('/users', methods=['POST'])
def create_user():
    limiter.limit('1 per day')
```

**Comment by alisaifee** [comment]
You can use the underlying [limits](https://github.com/alisaifee/limits) library directly.

**Comment by girst** [comment]
for anyone stumbling upon this, here's a (hacky) way of rate-limiting 'after the fact.

`app.want_to_limit` is an example Flask endpoint string (like the one to pass to `url_for`). 

This essentially calls the decorator as a normal function. This then returns another function which we pass the original view function to (the second pair of parenthesis). And this then finally returns a fresh, rate-limited view function with which we overwrite the old one. 

```
    app.view_functions['app.want_to_limit'] = limiter.limit(
        "15/minute",
        key_func=limiter.util.get_remote_address
    )(app.view_functions['app.want_to_limit'])
```

**Comment by alisaifee** [comment]
> How do you `get_remote_address` this way?
That recommendation is a bit out dated now. What use case are you exactly trying to solve where you can't use the decorator on a route?
