### ISSUE TITLE
Dynamically loaded limit string is having clash

### ISSUE THREAD

**Issue by pip-entertainer** [alisaifee/flask-limiter#208]
I'm following the [official docs](https://flask-limiter.readthedocs.io/en/stable/#decorators), for **Dynamically loaded limit string(s)**. Basically, I'm trying to implement company specific RATE LIMIT might be same as #53 and #64. Following is the presentation what I'm trying to do:

```
DEFAULT_LIMIT = "100/day, 10/minute"

app = Flask(__name__)

# defining limiter
limiter = Limiter(
    app,
    key_func=get_remote_address,
    default_limits=[DEFAULT_LIMIT] # this is default limit set for app
)

# company model
class Company(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(100), unique=True)
    limit = db.Column(db.String(50), default=DEFAULT_LIMIT)

    def __init__(self, name, limit):
        self.name = name
        self.limit = limit

def get_company_limit():
    try:
        company = Company.query.get(request.view_args['id'])
        return app.config.get("CUSTOM_LIMIT", company.limit)
    except:
        abort(403) # if company not found then raise forbidden

# an end point
@app.route("/company/<id>", methods=["GET"])
@limiter.limit(get_company_limit)
def get_company(id):
    return "success"

```
I've companies with information in db as follow:
```
[
    {
        "name": "company1"
        "limit": "100/day, 5/minute",
    },
    {
       "name": "company2"
        "limit": "100/day, 10/minute",
    },
    {
        "name": "company3"
        "limit": "50/day, 5/minute",
    },
    {
       "name": "company4"
        "limit": "100/day, 2/minute",
    }
]
```

Dynamically fetched limit is working fine with comapnies 1, 2 and 4. But as you can see there is some matching limit (5/minute) is for company1 and company3, limit is being shared for these companies whatever the the order of calling api end point. On hitting the end point, company1 and company3 share the limit counter of 5. 

For example if end point is called with company1 id for 3 times, on calling with the company3 id, after 2 success responses, limiter will raise 429. And also raise 429 for company1.

Unable to understand this behaviour and what I've missed to understand this?

**Comment by MianAzeem** [comment]
The problem is with:
```
# defining limiter
limiter = Limiter(
    app,
    key_func=get_remote_address,
    default_limits=[DEFAULT_LIMIT] # this is default limit set for app
)
```

Basically here, `get_remote_address` is used as key_func whcih is having clash with each new request. It might be returning the same remote address of the client's interface for each request. You need a user defined key_func to regulate the request. 

```
def get_comany_id():
    return (Company.query.get(request.view_args['id']), 0)

# defining limiter
limiter = Limiter(
    app,
    key_func=get_comany_id,
    default_limits=[DEFAULT_LIMIT] # this is default limit set for app
)
```

**Comment by pip-entertainer** [comment]
I get it now. @MianAzeem it worked.
