### ISSUE TITLE
Headers enabled by default

### ISSUE THREAD

**Issue by joshfriend** [alisaifee/flask-limiter#22]
The rate limit headers are [enabled by default](https://github.com/alisaifee/flask-limiter/blob/0.6.6/flask_limiter/extension.py#L111), which is contrary to the docs.

It might also be a good idea to enable RTD versioning, and set the default doc version to the latest pypi version.

**Comment by alisaifee** [comment]
Thanks @joshfriend.
Do you know of an automated way for RTD to pick up the latest version from pypi?

**Comment by joshfriend** [comment]
The admin section on RTD has a [versions](https://readthedocs.org/dashboard/flask-limiter/versions/) section where you can choose the active versions (with the checkboxes) and the default version to show when users visit http://flask-limiter.readthedocs.org.

If you have your base [settings](https://readthedocs.org/dashboard/flask-limiter/edit/) configured correctly, RTD should be able to pick up the git tags from your repo.

AFAIK, It doesn't pick up any info from PyPI, so you need to manually update the default version in the settings on new releases. Hope that helps!
