### ISSUE TITLE
Flask Limiter is not working in Shared Hosting

### ISSUE THREAD

**Issue by stenlytw** [alisaifee/flask-limiter#221]
I tried to incorporate `flask-limiter` into my Flask Application, it's working on localhost, but the rate limiter is not working on shared hosting.

Is there anyone experiences the same problem?

**Comment by stenlytw** [comment]
Is there any way to connect to Redis by Unix socket?

**Comment by alisaifee** [comment]
Hi @stenlytw. Currently there is no way to connect to redis over a unix socket. Are you still in need of this functionality?

**Comment by alisaifee** [comment]
Fixed in [limits@1.4.1](https://github.com/alisaifee/limits/releases)
