### ISSUE TITLE
LimitGroup signature breaking in version 1.2.0

### ISSUE THREAD

**Issue by ppanero** [alisaifee/flask-limiter#241]
In version 1.2.0 `override_defaults` is added to the object signature of `LimitGroup`, without any default value. Some of the object instantiations that happen on the code add this parameter, therefore any use of this in external code is breaking.

LimiterGroup (8 params):
``` python
def __init__(
        self, limit_provider, key_function, scope, per_method, methods,
        error_message, exempt_when, override_defaults
    ):
```

Example object creation in `extension.py` (line 237) has only 7.
``` python
LimitGroup(
    app_limits, self._key_func, "global", False, None, None,
    None
)
```

Made a PR (https://github.com/alisaifee/flask-limiter/pull/240) for the issue. Please check that the values passed make sense I am not ultra familiar with the code base.

**Comment by alisaifee** [comment]
Wow, thank you so much for catching this so quickly and offering a fix as well! The one line that wasn't covered by tests 😞

**Comment by ppanero** [comment]
My pleasure! thanks for the quick merge/release :rocket:
