### ISSUE TITLE
File system backend?

### ISSUE THREAD

**Issue by KeithCu** [alisaifee/flask-limiter#242]
Would it be useful to have a file system backend? I currently run a flask app on Apache, which spins up a pool of 7-30 processes to respond to requests. Clearly the memory cache is out. I could consider using Redis or Memcached, but I don't have those apps installed yet, and a file system could be faster, especially if it were just writing to the /tmp RAM drive. I know those apps are solid, but they are slower, and more complicated.

I could perhaps try to implement it, either building something based on flask-caching, or perhaps using some code from that plugin.

**Comment by randomstuff** [comment]
This one is probably an issue for the [limits](https://github.com/alisaifee/limits/issues) package.

**Comment by KeithCu** [comment]
Thanks for the info, I filed a bug there and will close this.
