### ISSUE TITLE
AttributeError: 'Module_six_moves_urllib_parse' object has no attribute 'urlparse' 

### ISSUE THREAD

**Issue by 10000TB** [alisaifee/flask-limiter#243]
Seeing this 

``` 
File "/Users/juanghowiej/Library/Python/2.7/lib/python/site-packages/flask_limiter/extension.py", line 199, in init_app
    **self._storage_options
  File "/Users/juanghowiej/Library/Python/2.7/lib/python/site-packages/limits/storage.py", line 33, in storage_from_string
    scheme = urllib.parse.urlparse(storage_string).scheme
AttributeError: 'Module_six_moves_urllib_parse' object has no attribute 'urlparse'
```

Anyone know what happened ?

**Comment by 10000TB** [comment]
looks like this will happen when you use latest flask-limiter in  py2, and `1.0.1` of flask-limiter is the version

**Comment by alisaifee** [comment]
I wasn't able to reproduce it with python2 but [this](https://stackoverflow.com/questions/29485741/unable-to-upgrade-python-six-package-in-mac-osx-10-10-2/29666702#29666702) article from stackoverflow might be a hint towards resolving what you're seeing.

**Comment by alisaifee** [comment]
@10000TB were you able to get this to work?

**Comment by 10000TB** [comment]
Yea, reverting it back and pinning the version works for me. Feel free to close
