### ISSUE TITLE
Is it possible to abort with a custom exception (no 429 code)?

### ISSUE THREAD

**Issue by Horace89** [alisaifee/flask-limiter#245]
The doc says : "The default configuration results in an abort(429) being called [...]".

Is it possible to customize this behaviour, for example:
- aborting with an other HTTP code
- raising a custom exception
- only logging the remote ip address

**Comment by alisaifee** [comment]
You can use the [Error handling mechanism](https://flask.palletsprojects.com/en/1.1.x/errorhandling/#error-handlers) from Flask to trap the error and raise your own etc, for example:

```python
@app.errorhandler(RateLimitExceeded) # or @app.errorhandler(429)
def handler(response):
    return "No!", 400
```

**Comment by Horace89** [comment]
Thanks!

**Comment by Enkumicahel** [comment]
How about disabling the exception log? Is it possible to do that?

**Comment by alisaifee** [comment]
> How about disabling the exception log? Is it possible to do that?

Are you referring to the warning level log (something like: ``ratelimit 1/second (127.0.0.1) exceeded at endpoint: /fubar``) that is emitted everytime a rate limit is exceeded?

**Comment by alisaifee** [comment]
This should work:

```
import logging
logging.getLogger("flask-limiter").setLevel(logging.ERROR) # or anything higher than logging.WARNING
```

**Comment by Enkumicahel** [comment]
This didn't work for me. Still seeing this 
`
...
flask_limiter.errors.RateLimitExceeded: 429 Too Many Requests: 5 per 1 minute
`

**Comment by alisaifee** [comment]
That doesn't appear to be coming from the extension but from something that is logging the flask error (non 200) response in your application

**Comment by Enkumicahel** [comment]
That's actually from `flask-liimiter` itself I believe. I have updated the log in its entirety.

**Comment by alisaifee** [comment]
> That's actually from `flask-liimiter` itself I believe. I have updated the log in its entirety.

The exception `RateLimitExceeded` is indeed raised by the extension - that is how the extension stops the request chain from reaching the request handler that you are protecting with the rate limit. If you look at the stack trace you shared, the logging of the exception is being done in flask itself. My guess is that there is a generic `errorhandler` registered which logs any `HTTPException` (`RateLimitExceeded` is a subclass of that).

**Comment by Enkumicahel** [comment]
@alisaifee thanks a lot!

**Comment by alisaifee** [comment]
> @alisaifee thanks a lot!

Glad it got cleared up! Just out of curiosity, what was doing the logging?

**Comment by Enkumicahel** [comment]
@alisaifee there was already an error handler by `@blueprint.app_errorhandler` decorated functions. I missed that and you got it right.
