### ISSUE TITLE
Feature Request: Ability to configure status code

### ISSUE THREAD

**Issue by jmunson** [alisaifee/flask-limiter#246]
I'm trying to integrate with a system out of my control that will retry requests on 5xx status codes, but not on 429 errors codes.

While I agree 429 is the right status code in general, being able to configure it would be very helpful in situations like these.

**Comment by alisaifee** [comment]
Though the status code is not directly configurable, you could do a workaround by registering an error handler the same was as in #245. Let me know if this works for you.

**Comment by jmunson** [comment]
That looks like a good solution for my needs. Thanks!
