### ISSUE TITLE
can't install to offline host from whl or tar.gz

### ISSUE THREAD

**Issue by mmaatibm** [alisaifee/flask-limiter#247]
Downloaded the package from https://pypi.org/ and uploaded to my host that is offline to internet (only intranet); but the installation fails as it is still trying to get simple limits.

unfortunately installing from the git repo zip "flask-limiter-master" also hangs there at:
"Reading https://pypi.org/simple/limits/"

Could you please include that to the package;
or should I install it to other host (that can access the internet) and rebuild to a new whl from that?

**Comment by rushilsrivastava** [comment]
This is because `limits` is a dependency. You need to install that as well.

**Comment by alisaifee** [comment]
To make sure you get all the transitive dependencies you could download the package (and its dependencies) using `pip` as follows:
```bash
mkdir packages
pip download -d ./packages  flask_limiter
tar czf packages.tar.gz packages
```
Then on the target offline host transfer `packages.tar.gz` from above and install the packages using something like the following:
```bash
tar zxf packages.tar.gz
pip install --no-index --find-links=./packages flask-limiter
```
