### ISSUE TITLE
Custom cost per route

### ISSUE THREAD

**Issue by bkanuka** [alisaifee/flask-limiter#272]
I'm writing an app with some routes that cost more computationally.  Therefore I would like some routes to deduct more than 1 from from quota every time the route is requested.  For example the limit decorator could take a `cost` parameter that by default is equal to 1, but could be set to someting like 5 if a request to that route costs 5 times as much as a standard request.

Expanding on this idea a bit, it would be interesting if the cost could be calculated from the Response rather than static per route.  This could enable the limiter to track "true" cost where the cost is something like CPU time.  So a request that costs a lot of CPU time would be fulfilled, and the Response made, but then before passing the result onto the end user, a certain amount is deducted from their quota.  I guess this could be implemented by having the `cost` parameter on the limiter accept a callable (which gets called with the flask response).

**Comment by alisaifee** [comment]
You can try the `cost=` attribute accepted by `limit` and `shared_limit`. 
https://flask-limiter.readthedocs.io/en/latest/api.html#flask_limiter.Limiter.shared_limit.params.cost
https://flask-limiter.readthedocs.io/en/latest/api.html#flask_limiter.Limiter.limit.params.cost

This is available starting `2.1.x`

**Comment by steveeyring** [comment]
@bkanuka I'm trying to do the same thing. Did you ever figure out a way to implement this?

**Comment by bkanuka** [comment]
i did not, i moved away from flask entirely.  But looks to me like this is implemented now.
