### ISSUE TITLE
How to set a custom cooldown when ratelimited?

### ISSUE THREAD

**Issue by actualdankcoder** [alisaifee/flask-limiter#274]
The docs didn't quite help me with this bit, it goes like
Assuming a user crosses the limit of "n requests per second",  how would one set the cooldown for x minutes.
I tried using the retry_after attribute but it didn't work

**Comment by solsticedhiver** [comment]
I want to do this too.

**Comment by alisaifee** [comment]
Unfortunately I can't think of a clean way to integrate this with the underlying implementation for rate limiting in [limits](https://github.com/alisaifee/limits). If this were to happen it would need to be implemented there first.
