### ISSUE TITLE
Google Cloud Tasks?

### ISSUE THREAD

**Issue by keremnymn** [alisaifee/flask-limiter#275]
Hello, 
I'll deploy my API onto GCP Compute Engine and I'll use Google Cloud Tasks for async tasks.
I've only seen tutorials about Redis.

Is it possible to use this with GCP Cloud Tasks? If so, what would be the steps?

Thanks in advance.

**Comment by alisaifee** [comment]
Unfortunately I don't use GCP myself - but happy to look at a pull request if it's still interesting.
