### ISSUE TITLE
How to rate limit without a decorator

### ISSUE THREAD

**Issue by CoburnJoe** [alisaifee/flask-limiter#277]
Based on discussion #195 it's possible to user the underlying Limits library to rate limit at arbitrary times during application logic, without using a decorator.

How would I go about using `limiter.hit` with my existing flask-limiter object? I don't want to reconfigure my app to use Limits directly, as I still need flask-limiter for many other Flask routes.

In short, I want to call the `hit` method of my flask-limiter object.

**Comment by CoburnJoe** [comment]
@alisaifee any suggestions?

**Comment by alisaifee** [comment]
given:
```
import limits

app = Flask(__name__)
limiter_ext = Limiter(app, .....)
```
you can do `limiter_ext.limiter.hit(limits.parse("1/second"), "fu", "bar")`
