### ISSUE TITLE
[ Question ] How to set maximum requests ? 

### ISSUE THREAD

**Issue by AyushSehrawat** [alisaifee/flask-limiter#280]
For example you have 3 roots

/ -> 1000 / hour
/a -> 1000 / hour
/b -> 1000 / hour

If someone use multi threading to attack all these 3 routes , he in total gets 3000/hour requests. Is it true ? Or how to fix?

**Comment by alisaifee** [comment]
You can add an application wide limit either by using the flask config https://flask-limiter.readthedocs.io/en/stable/configuration.html#RATELIMIT_APPLICATION or the extension argument: https://flask-limiter.readthedocs.io/en/stable/api.html#flask_limiter.Limiter.params.application_limits

For example:
```python
from flask import Flask
from flask_limiter import Limiter
from flask_limiter.util import get_remote_address

app = Flask(__name__)
limiter = Limiter(app, application_limits=["1000 per hour"], key_func=get_remote_address)


@app.route("/")
@limiter.limit("1000 per hour")
def root():
    return "root"


@app.route("/a")
@limiter.limit("1000 per hour")
def a():
    return "a"


@app.route("/b")
@limiter.limit("1000 per hour")
def b():
    return "b"


app.run()

```
