### ISSUE TITLE
Flask-Limiter is ignored on Flask version 2.0

### ISSUE THREAD

**Issue by alirezastack** [alisaifee/flask-limiter#287]
Due to `outside of context` issue I created a limiter function in a `util.py` file as follow:

```
def limiter():
    _limiter = Limiter(
        app,
        key_func=get_remote_address
    )
    return _limiter

```

And in my `Flask-Restful` API resource I have called this limiter in `method_decorators`:

```
from ..utils import limiter

class UsersView(Resource, CustomAPIMixin):
     method_decorators = [limiter().limit("1/minute", methods=["GET"])]

     @jwt_authenticate()
     def get(self):
         user_id = get_jwt_identity()
         return self.api_response(content={"user_id": user_id})

```

Flask: 2 
Flask-Limiter 1.4
OS: OS X 11.5

**Comment by kreathon** [comment]
Using `decorators` instead of `method_decorators` works for me.

```
from ..utils import limiter

class UsersView(Resource, CustomAPIMixin):
     decorators = [limiter().limit("1/minute", methods=["GET"])]

     @jwt_authenticate()
     def get(self):
         user_id = get_jwt_identity()
         return self.api_response(content={"user_id": user_id})
```

**Comment by alirezastack** [comment]
@kreathon there was 2 issues for me. One was changing `method_decorators` to `decorators` and also moving `decorators` from `UsersView` file to my routes file where I add view resources. By using rate limit in utils a new app context had been pushed to Flask stack so rate limiting did not work.
