### ISSUE TITLE
Update docs on 'Deploying an application behind a proxy'

### ISSUE THREAD

**Issue by FifthHour** [alisaifee/flask-limiter#290]
Hi,

Thank you for this package.

I noticed an outdated section of the docs and would be happy to raise a pull request to fix this.

**Current Docs:**

In the 'Deploying an application behind a proxy' section of the docs, the following code includes a werkzeug class which has been deprecated:

```
from flask import Flask
from flask_limiter import Limiter
from flask_limiter.util import get_remote_address
from werkzeug.contrib.fixers import ProxyFix

app = Flask(__name__)

app.wsgi_app = ProxyFix(app.wsgi_app, num_proxies=1)
limiter = Limiter(
    app,
    key_func=get_remote_address
)
```

**Proposed Change**
According the Werkzeug docs it should be:

```
from flask import Flask, request, jsonify
from flask_limiter import Limiter 
from flask_limiter.util import get_remote_address
from werkzeug.middleware.proxy_fix import ProxyFix


app = Flask(__name__)
app.wsgi_app = ProxyFix(app.wsgi_app, x_for=1)
limiter = Limiter(
    app,
    key_func=get_remote_address,
)
```

I have made this change in my code and it works.

Let me know if you can fix quickly yourself or if you want me to do a pull request

Many thanks

**Comment by FifthHour** [comment]
Is this still maintained and do you want me to help with a fix?

**Comment by alisaifee** [comment]
@FifthHour sorry for the enormous delay in getting back to you, if you could raise a PR I'd be happy to merge it in.

**Comment by FifthHour** [comment]
No worries! Great, I'll get onto that soon
