### ISSUE TITLE
Flask 2.0.x async view support

### ISSUE THREAD

**Issue by brunoratkaj** [alisaifee/flask-limiter#292]
Is there a plan to implement async view support?

**Comment by brunoratkaj** [comment]
I've opened a PR to tackle this issue - https://github.com/alisaifee/flask-limiter/pull/293

**Comment by alisaifee** [comment]
This won't be available in the 1.x releases, but I've dropped support for python < 3.7 in master, and will shortly cut an initial 2.x release.

**Comment by alisaifee** [comment]
Available in  2.0.0
