### ISSUE TITLE
Using SSL connection to redis

### ISSUE THREAD

**Issue by adiberk** [alisaifee/flask-limiter#294]
I am getting the following error:
`web_1           | Traceback (most recent call last):
web_1           |   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1948, in full_dispatch_request
web_1           |     rv = self.preprocess_request()
web_1           |   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 2242, in preprocess_request
web_1           |     rv = func()
web_1           |   File "/usr/local/lib/python3.9/site-packages/flask_limiter/extension.py", line 630, in __check_request_limit
web_1           |     six.reraise(*sys.exc_info())
web_1           |   File "/usr/local/lib/python3.9/site-packages/six.py", line 703, in reraise
web_1           |     raise value
web_1           |   File "/usr/local/lib/python3.9/site-packages/flask_limiter/extension.py", line 613, in __check_request_limit
web_1           |     self.__evaluate_limits(endpoint, all_limits)
web_1           |   File "/usr/local/lib/python3.9/site-packages/flask_limiter/extension.py", line 483, in __evaluate_limits
web_1           |     if not method(lim.limit, *args):
web_1           |   File "/usr/local/lib/python3.9/site-packages/limits/strategies.py", line 132, in hit
web_1           |     self.storage().incr(item.key_for(*identifiers), item.get_expiry())
web_1           |   File "/usr/local/lib/python3.9/site-packages/limits/storage.py", line 445, in incr
web_1           |     return self.lua_incr_expire([key], [expiry])
web_1           |   File "/usr/local/lib/python3.9/site-packages/redis/commands/core.py", line 3952, in __call__
web_1           |     return client.evalsha(self.sha, len(keys), *args)
web_1           |   File "/usr/local/lib/python3.9/site-packages/redis/commands/core.py", line 3515, in evalsha
web_1           |     return self.execute_command('EVALSHA', sha, numkeys, *keys_and_args)
web_1           |   File "/usr/local/lib/python3.9/site-packages/redis/client.py", line 1068, in execute_command
web_1           |     conn = self.connection or pool.get_connection(command_name, **options)
web_1           |   File "/usr/local/lib/python3.9/site-packages/redis/connection.py", line 1168, in get_connection
web_1           |     connection = self.make_connection()
web_1           |   File "/usr/local/lib/python3.9/site-packages/redis/connection.py", line 1208, in make_connection
web_1           |     return self.connection_class(**self.connection_kwargs)
web_1           |   File "/usr/local/lib/python3.9/site-packages/redis/connection.py", line 837, in __init__
web_1           |     super().__init__(**kwargs)
web_1           | TypeError: __init__() got an unexpected keyword argument 'ssl'`

I did some initial investigation and it seems it might actually be an issue with the redis library itself and it's implementation of **from_url**
However, flask-limiter can fix this by initiating redis using the __init__ instead of from url.  User can still pass in the url but we can parse it ourselves using this library:
from urllib.parse import urlparse

From here we can pass in all the arguments in the __init__ of Redis class

**Comment by alisaifee** [comment]
Thanks for the report! The details of specific backends is managed in the [limits](https://github.com/alisaifee/limits). To be fair, I had never actually done any testing with redis over ssl, but I've added some tests [here](https://github.com/alisaifee/limits/commit/5d7525427afbc272c164627a67083c8fd10b98dd) which verifies that it does work given the configuration in the tests. 

Having said that, happy to take this issue over to `limits` if there are any improvements that can be made.

**Comment by Enkumicahel** [comment]
If it can help someone:
Following the first paragraph of [this](https://flask-limiter.readthedocs.io/en/stable/configuration.html)
1. Remove the `RATELIMIT_STORAGE_URI` from settings.py
2. Defining `RATELIMIT_STORAGE_OPTIONS` in `settings.py` and giving it the following dict
> REDIS = {
>     'host': '100.100.100.100',
>     'port': 6379,
>     'password': 'password',
>     'ssl': True,
>     'ssl_cert_reqs': 'required',
>     'ssl_ca_certs': 'path to pem file',
> }
