### ISSUE TITLE
limit as a fraction

### ISSUE THREAD

**Issue by yiga2** [alisaifee/flask-limiter#304]
It is unclear from the documentation if the limit can be like `1/2secs` or `1 per 2sec(s)`. I want to implement such limit (per user) as a way to block bots vs. human.
If such notation is possible i.e. count per multiple time-units, the documentation should be amended with the syntax to use (sec/secs, min/mins,...).

**Comment by yiga2** [comment]
Answering if possible: yes as per the regex `SINGLE_EXPR` @ https://limits.readthedocs.io/en/latest/_modules/limits/util.html#parse
Matching limits:
```
"1 / 2 second" (or seconds)
"1 per 2 seconds"
```
Would be good to add such case explicitly in the Flask-limiter lib documentation

**Comment by alisaifee** [comment]
Thanks, documentation updated here: https://flask-limiter.readthedocs.io/en/latest/configuration.html#rate-limit-string-notation
