### ISSUE TITLE
Memcached backed limiter produces unexpected results running multi-machine

### ISSUE THREAD

**Issue by zacharyozer** [alisaifee/flask-limiter#31]
Hi,

We're seeing some very strange behavior when running flask-limiter in the following environment (backed by memcache):

![compass architechture](https://cloud.githubusercontent.com/assets/1268023/8361963/16e899ee-1b44-11e5-8bab-a782e460c0bf.png)

With a limit of 30 requests per minute, I see the following when printing out the flask-limiter debug headers:
```
iteration: 0, remaining 29, headers {'x-ratelimit-limit': '30', 'x-ratelimit-reset': '1435256060'}
iteration: 1, remaining 29, headers {'x-ratelimit-limit': '30', 'x-ratelimit-reset': '1435256061'}
iteration: 2, remaining 28, headers {'x-ratelimit-limit': '30', 'x-ratelimit-reset': '1435256061'}
iteration: 3, remaining 27, headers {'x-ratelimit-limit': '30', 'x-ratelimit-reset': '1435256061'}
iteration: 4, remaining 26, headers {'x-ratelimit-limit': '30', 'x-ratelimit-reset': '1435256061'}
iteration: 5, remaining 25, headers {'x-ratelimit-limit': '30', 'x-ratelimit-reset': '1435256061'}
iteration: 6, remaining 24, headers {'x-ratelimit-limit': '30', 'x-ratelimit-reset': '1435256061'}
iteration: 7, remaining 28, headers {'x-ratelimit-limit': '30', 'x-ratelimit-reset': '1435256060'}
iteration: 8, remaining 29, headers {'x-ratelimit-limit': '30', 'x-ratelimit-reset': '1435256072'}
iteration: 9, remaining 23, headers {'x-ratelimit-limit': '30', 'x-ratelimit-reset': '1435256061'}
iteration: 10, remaining 27, headers {'x-ratelimit-limit': '30', 'x-ratelimit-reset': '1435256060'}
iteration: 11, remaining 26, headers {'x-ratelimit-limit': '30', 'x-ratelimit-reset': '1435256060'}
iteration: 12, remaining 22, headers {'x-ratelimit-limit': '30', 'x-ratelimit-reset': '1435256061'}
iteration: 13, remaining 21, headers {'x-ratelimit-limit': '30', 'x-ratelimit-reset': '1435256061'}
iteration: 14, remaining 20, headers {'x-ratelimit-limit': '30', 'x-ratelimit-reset': '1435256061'}
iteration: 15, remaining 19, headers {'x-ratelimit-limit': '30', 'x-ratelimit-reset': '1435256061'}
iteration: 16, remaining 28, headers {'x-ratelimit-limit': '30', 'x-ratelimit-reset': '1435256072'}
iteration: 17, remaining 27, headers {'x-ratelimit-limit': '30', 'x-ratelimit-reset': '1435256072'}
iteration: 18, remaining 26, headers {'x-ratelimit-limit': '30', 'x-ratelimit-reset': '1435256072'}
iteration: 19, remaining 18, headers {'x-ratelimit-limit': '30', 'x-ratelimit-reset': '1435256061'}
iteration: 20, remaining 17, headers {'x-ratelimit-limit': '30', 'x-ratelimit-reset': '1435256061'}
iteration: 21, remaining 16, headers {'x-ratelimit-limit': '30', 'x-ratelimit-reset': '1435256061'}
iteration: 22, remaining 15, headers {'x-ratelimit-limit': '30', 'x-ratelimit-reset': '1435256061'}
iteration: 23, remaining 14, headers {'x-ratelimit-limit': '30', 'x-ratelimit-reset': '1435256061'}
iteration: 24, remaining 25, headers {'x-ratelimit-limit': '30', 'x-ratelimit-reset': '1435256060'}
iteration: 25, remaining 25, headers {'x-ratelimit-limit': '30', 'x-ratelimit-reset': '1435256072'}
iteration: 26, remaining 24, headers {'x-ratelimit-limit': '30', 'x-ratelimit-reset': '1435256060'}
iteration: 27, remaining 23, headers {'x-ratelimit-limit': '30', 'x-ratelimit-reset': '1435256060'}
iteration: 28, remaining 13, headers {'x-ratelimit-limit': '30', 'x-ratelimit-reset': '1435256061'}
iteration: 29, remaining 12, headers {'x-ratelimit-limit': '30', 'x-ratelimit-reset': '1435256061'}
iteration: 30, remaining 22, headers {'x-ratelimit-limit': '30', 'x-ratelimit-reset': '1435256060'}
iteration: 31, remaining 24, headers {'x-ratelimit-limit': '30', 'x-ratelimit-reset': '1435256072'}
iteration: 32, remaining 11, headers {'x-ratelimit-limit': '30', 'x-ratelimit-reset': '1435256061'}
iteration: 33, remaining 21, headers {'x-ratelimit-limit': '30', 'x-ratelimit-reset': '1435256060'}
iteration: 34, remaining 20, headers {'x-ratelimit-limit': '30', 'x-ratelimit-reset': '1435256060'}
iteration: 35, remaining 10, headers {'x-ratelimit-limit': '30', 'x-ratelimit-reset': '1435256061'}
iteration: 36, remaining 9, headers {'x-ratelimit-limit': '30', 'x-ratelimit-reset': '1435256061'}
iteration: 37, remaining 19, headers {'x-ratelimit-limit': '30', 'x-ratelimit-reset': '1435256060'}
iteration: 38, remaining 8, headers {'x-ratelimit-limit': '30', 'x-ratelimit-reset': '1435256061'}
iteration: 39, remaining 7, headers {'x-ratelimit-limit': '30', 'x-ratelimit-reset': '1435256061'}
iteration: 40, remaining 18, headers {'x-ratelimit-limit': '30', 'x-ratelimit-reset': '1435256060'}
iteration: 41, remaining 6, headers {'x-ratelimit-limit': '30', 'x-ratelimit-reset': '1435256061'}
iteration: 42, remaining 5, headers {'x-ratelimit-limit': '30', 'x-ratelimit-reset': '1435256061'}
iteration: 43, remaining 29, headers {'x-ratelimit-limit': '30', 'x-ratelimit-reset': '1435256120'}
iteration: 44, remaining 28, headers {'x-ratelimit-limit': '30', 'x-ratelimit-reset': '1435256120'}
iteration: 45, remaining 23, headers {'x-ratelimit-limit': '30', 'x-ratelimit-reset': '1435256072'}
iteration: 46, remaining 27, headers {'x-ratelimit-limit': '30', 'x-ratelimit-reset': '1435256120'}
iteration: 47, remaining 22, headers {'x-ratelimit-limit': '30', 'x-ratelimit-reset': '1435256072'}
iteration: 48, remaining 21, headers {'x-ratelimit-limit': '30', 'x-ratelimit-reset': '1435256072'}
iteration: 49, remaining 29, headers {'x-ratelimit-limit': '30', 'x-ratelimit-reset': '1435256128'}
iteration: 50, remaining 26, headers {'x-ratelimit-limit': '30', 'x-ratelimit-reset': '1435256120'}
```
Any idea what might be causing this?

Thanks!

**Comment by lukas-gitl** [comment]
We have a very similar setup and I can't reproduce your issue (we just have one Elasticache instance). How many EC2 instances do you have running in ELB? Are all those instances connected to the same Elasticache instance? Are all the threads in the flask processes connected to the same Elasticache instance? Seems to be a problem where instances / processes are talking to different Elasticache instances.

Can you debug what get's written to your Elasticache?

**Comment by zacharyozer** [comment]
We have 3 instances in the ELB. The flask processes on all 3 instances have been configured to connect to the same Elasticache cluster (which also has 3 nodes).

Would love to debug what's being written to the Elastichache, but I didn't see a good way to do this. Is there some configuration option I can enable to get additional logging / print statements? If no, is there a deterministic way to calculate the key being sent to Memcache such that I can read it manually?

**Comment by lukas-gitl** [comment]
Can you spin up a test environment to experiment? And then maybe try to
list the keys, e.g.:
http://www.darkcoding.net/software/memcached-list-all-keys/

On 25 June 2015 at 13:17, Zachary Ozer <notifications@github.com> wrote:

> We have 3 instances in the ELB. The flask processes on all 3 instances
> have been configured to connect to the same Elasticache cluster (which also
> has 3 nodes).
>
> Would love to debug what's being written to the Elastichache, but I didn't
> see a good way to do this. Is there some configuration option I can enable
> to get additional logging / print statements? If no, is there a
> deterministic way to calculate the key being sent to Memcache such that I
> can read it manually?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/alisaifee/flask-limiter/issues/31#issuecomment-115383789>
> .
>



-- 

Lukas Siemon
Technical Lead / Software Engineer

[image: GetintheLoop] <https://getintheloop.ca>

Intelligent Mobile Marketing

Phone: (250) 801 0445 <2508010445>
Email: lukas@getintheloop.ca
Website: getintheloop.ca

[image: Facebook] <https://facebook.com/getintheloopca> [image: Twitter]
<https://twitter.com/getintheloopca> [image: Google+]
<https://plus.google.com/107252085651373281158> [image: Instagram]
<http://instagram.com/getintheloopca> [image: Linkedin]
<https://www.linkedin.com/company/2229906>

**Comment by zacharyozer** [comment]
I've got a few environments to test against. What sort of experiment should I be running?

I've started dumping keys and found something somewhat surprising. When I try to read out keys, I only seem to get values when reading from the /day bucket:

```
> get VALUE LIMITER/<user_id>/customer_listing.view/300/1/day 0 1
6
END
> get LIMITER/<user_id>/customer_listing.view/30/1/minute
END
> get LIMITER/<user_id>/customer_listing.view/30/1/minute/expires
END
```

Am I just to slow? Is this expected?

**Comment by zacharyozer** [comment]
We've done some further tests and we now believe this is a result of the fact that we're using a multi-AZ Elasticache configuration. We're contacting Amazon to see what they say. I will update once we've heard back.

**Comment by lukas-gitl** [comment]
Sorry I didn't have time to get back to you yesterday. The keys you tested above seem fine. It would be interesting to see how they change as you keep reaching your limit. That code is well tested, so I don't think there is an issue there.

I'm not sure how multi-AZ would cause problems. However if different caches are hit, then that would cause the behaviour that you're describing. Let me know when you hear back from Amazon!

**Comment by alisaifee** [comment]
@zacharyozer : sorry for the delayed response. To try and reduce the variables would it be possible for you to run an experiment that:
* increments a key in a `before_request` handler attached to your app 
* retrieves the value in an `after_request` handler and logs it

Also, which strategy are you using?

**Comment by zacharyozer** [comment]
We're using the fixed window strategy. Still waiting to hear back from AWS, so we're going to move to a single AZ cache temporarily. Will let you know if this resolves the issue.

**Comment by zacharyozer** [comment]
Single AZ cache seems to have resolved the issue. Still no word back from Amazon.
