### ISSUE TITLE
Installation with extra redis doesn't install redis

### ISSUE THREAD

**Issue by it-ony** [alisaifee/flask-limiter#332]
I execute `pip install "Flask-Limiter[redis]"`
and get `WARNING: flask-limiter 2.3.0 does not provide the extra 'redis'`.

**Comment by alisaifee** [comment]
Thanks for the report. This is pretty bizarre, seems like I never actually added that in the package and only in the documentation 🤦. I'll cut a 2.3.1 release shortly to address this.

**Comment by alisaifee** [comment]
Resolved in [2.3.1](https://flask-limiter.readthedocs.io/en/latest/changelog.html#v2-3-1)

**Comment by it-ony** [comment]
Thanks for fixing this so quickly.
