### ISSUE TITLE
Issue at Litespeed server and Python 3.9.12

### ISSUE THREAD

**Issue by sukhoi47** [alisaifee/flask-limiter#342]
Hi,

I am facing an intermittent issue with flask-limiter running on Python 3.9.12 on a Litespeed server.

Sometimes the web page loads, but most of the time, does not load.
You can see the attached images... Loaded in the first access (counter = 1), but in the second time, after a page reload (at browser), it keep trying to load, and after some time returns "Request Timeout" error.

Here is the full python code:

```
from flask import Flask, request
from flask_limiter import Limiter
from flask_limiter.util import get_remote_address

app = Flask(__name__)
limiter = Limiter(app, key_func=get_remote_address, default_limits=['300/day'], enabled=True)


counter = 0
@app.route('/')
@limiter.limit('200 per day')
@limiter.limit('50 per hour')
@limiter.limit('10 per minute')
def hello_world():
    global counter
    counter = counter + 1
    return f'Hello World! Visit number: {counter}'


if __name__ == '__main__':
    app.run()

```

If I set enabled=False then the problem disappears:
`limiter = Limiter(app, key_func=get_remote_address, default_limits=['300/day'], enabled=False)`

My best guess is some incompatibility with Litespeed server and/or its native WSGI.
Any idea on how to fix?

![flask-liimiter-problem](https://user-images.githubusercontent.com/22125794/172263364-2bf5b862-217c-4df4-93ec-634bbe4adfe8.jpg)
![flask-liimiter-problem-2](https://user-images.githubusercontent.com/22125794/172263369-47215604-49c0-454d-98a4-1f7d6095b633.jpg)
.

**Comment by sukhoi47** [comment]
Hi alisaifee!

I implemented your suggestion:
`limiter = Limiter(app, key_func=get_remote_address, swallow_errors=True, default_limits=['300/day'], enabled=True)`

And had the same problem.
The only thing at the ERROR LOG (stderr.log) is:
```

[UID:1476][2437956] Child process with pid: 2437989 was killed by signal: 15, core dumped: no
[UID:1476][2437956] Child process with pid: 2437992 was killed by signal: 15, core dumped: no
[UID:1476][2437956] Child process with pid: 2437990 was killed by signal: 15, core dumped: no
[UID:1476][2437956] Child process with pid: 2437991 was killed by signal: 15, core dumped: no
[UID:1476][2437956] Child process with pid: 2437993 was killed by signal: 15, core dumped: no
[UID:1476][2437956] Child process with pid: 2448122 was killed by signal: 15, core dumped: no
[UID:1476][2437956] Child process with pid: 2448123 was killed by signal: 15, core dumped: no
[UID:1476][2437956] Child process with pid: 2448125 was killed by signal: 15, core dumped: no
[UID:1476][2437956] Child process with pid: 2448124 was killed by signal: 15, core dumped: no
[UID:1476][2437956] Child process with pid: 2448126 was killed by signal: 15, core dumped: no

```

I could not locate other error logs.


I also tried Python 3.7 and 3.8, and had the same problem on the server.


Also, I created my own **key_func** to test if the problem was coming from `get_remote_address`, and, again, had the same problem:

```

def minhafuncao():
    visitor = 'dsofowersoefnsodhfoweh'
    return visitor

limiter = Limiter(app, key_func=minhafuncao, default_limits=['300/day'], enabled=True)

```


I did other tests and could confirm the problem is coming from this code:
`limiter = Limiter(app, key_func=get_remote_address, default_limits=['300/day'], enabled=True)`



To replicate the problem I think you will need a server with Cloudlinux + Litespeed + DirectAdmin web control panel
Then, at DirectAdmin interface, go to **Setup Python App** to create a new web application, and follow the steps to create.
Then, install the packages requirements, and restart the web application.

**Comment by alisaifee** [comment]
The extension by default will not log to any handler - you'll have to enable that in your app:
https://flask-limiter.readthedocs.io/en/stable/recipes.html#logging

**Comment by sukhoi47** [comment]
Running in my local computer, the app generated the following log (of which seems the logging is correctly implemented):
`[2022-06-07 20:10:03,338] flask-limiter                  WARNING  ratelimit 10 per 1 minute (127.0.0.1) exceeded at endpoint: index [__evaluate_limits:938]`

That was in my local computer (Windows 10), that I use for the development and where Flask-Limiter works pretty well.

But in the server, nothing was logged by "flask-limiter".

**Comment by sukhoi47** [comment]
I just upgraded flask-limiter to version 2.4.6 and the problem stands.

**Comment by sukhoi47** [comment]
After an initial test, seems the issue does not exists on Flask-Limiter version 2.4.3.
Version 2.4.4 and above, all have the issue.

I am still testing to confirm...

**Comment by alisaifee** [comment]
> After an initial test, seems the issue does not exists on Flask-Limiter version 2.4.3. Version 2.4.4 and above, all have the issue.
> 
> I am still testing to confirm...

That's an interesting lead. I tried (very little) to try and setup litespeed using docker but didn't have enough time to see it through.

It's a bit surprising that the issue appears between 2.4.3 and 2.4.4 since there wasn't any (intended) functional change there. In fact 2.4.1 - 2.4.6 all just contain chores related to the release process. The last major changes appeared in 2.4.0 where there was some refactoring related to how rate limits are resolved ([reference](https://flask-limiter.readthedocs.io/en/stable/changelog.html#v2-4-0))

**Comment by sukhoi47** [comment]
> > After an initial test, seems the issue does not exists on Flask-Limiter version 2.4.3. Version 2.4.4 and above, all have the issue.
> > I am still testing to confirm...
> 
> That's an interesting lead. I tried (very little) to try and setup litespeed using docker but didn't have enough time to see it through.
> 
> It's a bit surprising that the issue appears between 2.4.3 and 2.4.4 since there wasn't any (intended) functional change there. In fact 2.4.1 - 2.4.6 all just contain chores related to the release process. The last major changes appeared in 2.4.0 where there was some refactoring related to how rate limits are resolved ([reference](https://flask-limiter.readthedocs.io/en/stable/changelog.html#v2-4-0))

Unfortunately I said too early...
Version 2.4.3 worked for a while, but started to have the same issue. 
That is part of the problem, it is intermittent... in a very simple app like "hello world" the issue will appear in 5% of the access. In a more complex app it shows-up about for about 95% of the requests.

**Comment by alisaifee** [comment]
It's surprising that there aren't any more logs or traces available (having said that I have no idea how litespeed / directadmin are supposed to be used). Based on what you shared the process is getting a SIGTERM so perhaps a timeout? The configuration you've shared is using the in memory storage which eliminates problems connecting to a redis or memcached.

One idea to try and find out what the error is is to disable the regular `before_request` flow by doing something like the following:

```python
from flask import Flask, request
from flask_limiter import Limiter
from flask_limiter.util import get_remote_address

app = Flask(__name__)
limiter = Limiter(app, key_func=get_remote_address, enabled=True, auto_check=False)


counter = 0
@app.route('/')
@limiter.limit('1 per day')
def hello_world():
    try:
        limiter.check()
    except Exception as e:
        print(e)
    global counter
    counter = counter + 1
    return f'Hello World! Visit number: {counter}'


if __name__ == '__main__':
    app.run()
```

**Comment by alisaifee** [comment]
Another thing you could try is to completely remove the extension and simply return a 429 from a flask app and see if that works allright?

**Comment by sukhoi47** [comment]
> 

I tested your code. I am not sure on where to insert the `before_request`, then I did not used it.

I run the script until the issue appeared and generated a `Time out (500 Internal Server Error)` in the browser. At the same time `stderr.log` logged the following error:
`[UID:1476][557395] Child process with pid: 561712 was killed by signal: 15, core dumped: no`

Nothing was generated by the `print(e)` code.

I can repeat the test if I should insert the `before_request` code.

**Comment by sukhoi47** [comment]
I tested all flask-limiter versions down to version 1.0.1.

Version 1.0.1 generated `Error 500` because of some parameters in my code that were not implemented in such version (enabled=True, ...)

Interesting is that in versions 1.3.1 and 1.4 the issue is much smaller. If I do 2 or 3 reloads on the page, it ends-up loading properly. It is a similar behavior I can see in some websites at internet.

**Comment by sukhoi47** [comment]
> Based on what you shared the process is getting a SIGTERM so perhaps a timeout? 

Based on what I could see so far, the issue is because the server is unable to load/provide some resources in the page.
In this case, "resources" are the elements to construct the web page, such as text, images, CSS, etc. 

If we have a web page that is just a "hello world", then the issue is less frequent, because it has essentially just a short HTML plain text (one resource). Have to reload the "hello world" 20 times to see the issue.

If the webpage is more complex, loaded with many resources (HTML, images, CSS, etc.), then the issue is very frequent because it may affect any of the page resources, or a number of them. Sometimes does not load anything (likely HTML affected), in other cases does not load some of the images, or does not load the CSS file. 
Sometimes the issue is the image(s), other times the CSS, the HTML... and that erratic behavior happens without change the python code.

**Comment by sukhoi47** [comment]
> Another thing you could try is to completely remove the extension and simply return a 429 from a flask app and see if that works allright?


I tested that and seems it is working properly.
```

from flask import Flask, abort

app = Flask(__name__)

@app.route('/')
def hello_world():
    abort (429)

if __name__ == '__main__':
    app.run()

```


![test 429](https://user-images.githubusercontent.com/22125794/172669739-725cccec-1c75-44e2-aa4f-6647f93519e4.jpg)

**Comment by sukhoi47** [comment]
> Sure, I can jump into a quick call. I'm in the pacific timezone (UTC - 7)

I will email you at ali@xxxxxxxxxx.org

**Comment by alisaifee** [comment]
@sukhoi47 there is not much I can think of doing regarding the in memory storage having issues with litespeed. If / when you are satisfied with the "workaround" to use memcached or redis, please close this issue.
