### ISSUE TITLE
Custom route-based Jinja response on breach

### ISSUE THREAD

**Issue by Glandos** [alisaifee/flask-limiter#350]
The current recipe shows that it is possible to add an error handler **globally**. In my use case, I'd like to handle failed login attempts with a nice Jinja template page. It seems that there is nothing to do that from the limiter decorator, since `on_breach` result is ignored.
One idea is to use the error handler on `[RateLimitExceeded](https://flask-limiter.readthedocs.io/en/stable/api.html#flask_limiter.RateLimitExceeded)` and return the Jinja template here, but… we need to attach some data in this error to provide the actual route and info needed for generating the template.

Any ideas?

**Comment by alisaifee** [comment]
Yeah looks like this is a gap in the implementation.
I haven't thought about this or tested it out but perhaps expanding the definition of `on_breach` to either be a callable that returns nothing, or a `Response`. If a `Response` is returned it will be the one returned instead of raising the `RateLimitedExceeded` error.

**Comment by alisaifee** [comment]
Turns out in fact that instances of `HTTPException` (which `RateLimitExceeded` is a subclass of) will accept a `Response` object upon construction and render that if provided.

**Comment by Glandos** [comment]
Very interesting and promising! But this has to be supported by Flask-Limiter itself, am I right?

**Comment by alisaifee** [comment]
> Very interesting and promising! But this has to be supported by Flask-Limiter itself, am I right?

Yes that is correct. I've pushed a change to master @ d5a7e9469f114a150bb6f69b1b34e626874e2521 that exposes this functionality + some updates to the associated [recipes/examples](https://flask-limiter.readthedocs.io/en/latest/recipes.html#for-specific-rate-limit-decorated-routes). I'd appreciate it if you can take a look to see if this does satisfy your use case. 

You can test it out by installing the dev version from [test.pypi.org](https://test.pypi.org/project/Flask-Limiter/2.5.1.post0.dev2/) but I'll probably do a `2.6` release later today

**Comment by alisaifee** [comment]
Solution to this was released in [2.6.0](https://flask-limiter.readthedocs.io/en/stable/changelog.html#v2-6-0). Some examples in the recipes section [here](https://flask-limiter.readthedocs.io/en/stable/recipes.html#custom-rate-limit-exceeded-responses)
