### ISSUE TITLE
Limiter not limiting route to correct rate in mod_wsgi enviroment.

### ISSUE THREAD

**Issue by JohnBioinf** [alisaifee/flask-limiter#354]
I set up a flask server for which one route should be rate limited to 1 request per day from the outside, but for visitors from within the internal network have an unlimited rate.

The code roughly looks like so.

``` python
from flask import request
from flask_limiter import Limiter
from flask_limiter.util import get_remote_address

def visitor_has_no_restriction():
    """Check if visitor is from specified range list."""
    return any((ip_address(request.remote_addr) in net for net in UNI_NETS))

UNI_NETS = [ip_network(server_parameters["uni_net_space"])]
TIME_LIMIT = "1 per day"
LIMITER = Limiter(
    app,
    key_func=get_remote_address
)

@app.route("/limit_route/", methods=["post", "get"])
@LIMITER.limit(
    TIME_LIMIT,
    exempt_when=visitor_has_no_restriction,
)
def handle_route():
    """Will do stuff only once per day."""
    stuff()
    return redirect(url_for("show progress"))
```

In a local enviroment this works perfectly fine but when the apache server is started the limit will only get triggered if I use the route 5 times. The config of the apache server has:

```
WSGIDaemonProcess RNAcode_web user=apache group=apache threads=5
```

Could it be that each thread stores its own  "how-visted-the-site" list?  If so how to set it up that they share this list?

If not what did I do wrong?

Thanks
John

**Comment by alisaifee** [comment]
For production you should use an out of process storage such as memcached or redis. The default in memory storage is only meant for testing.

**Comment by FantasticMrFux** [comment]
Ah thanks. I should have read the documentation more carefully.

**Comment by JohnBioinf** [comment]
Ah thanks. I should have read the documentation more carefully.

**Comment by alisaifee** [comment]
Closing as no action pending
