### ISSUE TITLE
Specify minimum version of `typing_extensions`

### ISSUE THREAD

**Issue by cp2004** [alisaifee/flask-limiter#359]
In this package, there is a `typing_extensions` dependency but it has no minimum version requested. However, it depends on imports introduced in a newer version than 3.7.4.3 (probably in 4.x) of that package, so the main requirements file should probably specify at least `typing_extensions>=4`?

I am not sure exactly what the minimum version is or if it has been left unpinned for a reason, so I haven't created a PR.

**Comment by cp2004** [comment]
Having typed that, I see that `rich` *does* have a specified minimum, and that in turn specifies `typing-extensions>=4.0.0,<5`, so that should be installed...

The reason I opened this issue was that for some reason `typing-extensions` 3.7.4.3 was installed on an OctoPrint user's install while installing this package - I now have no idea why it wouldn't have been updated.

**Comment by alisaifee** [comment]
You're right there should be a minimum version (I think `>= 4.0` is safe enough)

**Comment by alisaifee** [comment]
Should be addressed in the next release (commit: e7a26bd45efc85484ad27d198eefaae376e532d0)

**Comment by cp2004** [comment]
Thank you very much for the fast response.

We're still ultimately baffled by why pip isn't installing the newer version for some users - I'm tempted to put it down to a pip bug, potentially with the old (pre-2020) dependency resolver as it looks like there's a few dependencies in the tree that require typing-extensions and pip is only paying attention to one of them? Who knows.

I'll get out of your way now 🙂.

**Comment by alisaifee** [comment]
No worries! I've just released [2.6.3](https://github.com/alisaifee/flask-limiter/releases/tag/2.6.3) which contains the minimum constraint so hopefully this resolves the issue for the OctoPrint user(s).
