### ISSUE TITLE
How to check the current limit status of an specific endpoint and key

### ISSUE THREAD

**Issue by Lost-MSth** [alisaifee/flask-limiter#361]
It is a question about #323 .

My example is that I use this project to limit the users' download actions. Firstly the client will get some download links from one endpoint (endpoint 1) and then download them from (endpoint 2) in sequence. It is surely two endpoints but only the error messages from endpoint 1 can be handled successfully by the client. So the function of endpoint 1 should get the limit status of endpoint 2.

I am a beginner and my solution is: (In endpoint 1. 'download' is endpoint 2.)
```python
try:
    g.user = user  # key_func = lambda: str(g.user)    // I use thread global 'g' to pass on user identity.
    limiter._Limiter__evaluate_limits('download', limiter._Limiter__filter_limits('download', ''))
except RateLimitExceeded:
...
```

I think it is not beautify and this solution will make an extra 'hit' when downloading. So I wonder if there is a better solution or if there are some useful APIs to get the limit status. Thanks.

**Comment by alisaifee** [comment]
I wonder if you could use the [shared_limit](https://flask-limiter.readthedocs.io/en/stable/#reusable-limits) for this use case?

**Comment by alisaifee** [comment]
Other than using the shared_limit mentioned earlier, I can't think of any elegant way for the rate limits under different routes to interact.

**Comment by Lost-MSth** [comment]
Yes, I have considered using the `shared_limit`, but another problem arises.

Two endpoints use different ways to do authentication. However, `key_func` of limiter is the user's id. So I should handle tokens before the limiter works. 

What I do is use special decorators:
```python
@api.route('endpoint 1', ...)
@login_required
@limiter...
# --------------
@api.route('endpoint 2', ...)
@download_token_handler
@limiter...
```
So it is not beautiful too. Most of the codes are in the decorators and the view/endpoint functions are almost empty. If I have many different authentication methods, the thing will be worst.

My idea is that if there is a way to delayed using the limiter, not just before every view function.

**Comment by alisaifee** [comment]
> My idea is that if there is a way to delayed using the limiter, not just before every view function.

I don't think I exactly understand what you mean by that - but if you want to get manual control over the rate limiting and not use the `limit` or `shared_limit` decorator then you could implement your own request lifecycle hooks like `before_request` and use the underlying the rate limiter directly by using the [limits](https://github.com/alisaifee/limits) library.

**Comment by Lost-MSth** [comment]
Great. Maybe the better way is to realize a limiter via using `limits` module.

Sorry to disturb you. And thank you very much.
