### ISSUE TITLE
RateLimitExceeded's optional response is not optional

### ISSUE THREAD

**Issue by RandomSegFault** [alisaifee/flask-limiter#362]
The optional `response` parameter to `RateLimitExceeded`'s constructor that was added in commit [d5a7e9469f114a150bb6f69b1b34e626874e2521](https://github.com/alisaifee/flask-limiter/commit/d5a7e9469f114a150bb6f69b1b34e626874e2521) is not optional since it has no default value.

**Comment by alisaifee** [comment]
Fixed in e45005c72cecd54a40e57a3aef92a3fc353f5227

**Comment by RandomSegFault** [comment]
Awesome, thanks for the quick fix !
