### ISSUE TITLE
on_breach callbacks in the limit decorator fail silently if they don't take the right number of arguments

### ISSUE THREAD

**Issue by afontenot** [alisaifee/flask-limiter#367]
With Flask 2.2.2 and Flask-Limiter 2.7.0.

I have a decorator that looks like

```python
@limiter.limit("1 per 10 seconds", on_breach=_error_responder)
```

And the corresponding callback

```python
def _error_responder(e):
    return make_response(render_template("example.html"), 429)
```

This works, but if I remove the `e` parameter from the callback, I get the default 429 page from flask-limiter instead. This is surprising because I expected to receive some kind of error if flask-limiter failed to call the callback. Instead everything "works", I just get the wrong error response.

**Comment by alisaifee** [comment]
At the moment any errors calling the callback will only be logged as a warning, but I agree by default this should fail loudly and perhaps only log if `swallow_errors` is set to True.

**Comment by alisaifee** [comment]
Are you using any kind of type checking in your code btw? This should have triggered an error with mypy or pyright.

**Comment by afontenot** [comment]
@alisaifee I'm not, unfortunately. I should probably look into that. My experience with Python predates the typing annotations so it's one of those things I just never learned.

Incidentally, are there other parts of flask-limiter that currently fail quietly? I have limit decorators with custom limits and custom `key_func`, and if either of those were broken my intended limits would probably fail in ways that are hard to detect without extensive testing on hardware capable of generating the necessary amount of load.

I don't remember seeing a warning. I'll have to try again with flask in debug mode when I get a chance. (My code sets a `RotatingFileHandler` as the app log handler via `addHandler`, if that tells you anything.)

**Comment by alisaifee** [comment]
Regarding other parts of the code that fail silently (I had to double check this in code) - the `on_breach` callback path is the only place where bare exceptions are caught and not re-raised (unless `swallow_errors` is enabled).

**Comment by alisaifee** [comment]
Regarding logging, perhaps the reason you're not seeing any logs is because you're only attaching a handler to the flask application and not the root logger or the extension's own logger. The extension does not automatically use the logger of the flask application. Some more details [here](https://flask-limiter.readthedocs.io/en/stable/recipes.html#logging)

**Comment by alisaifee** [comment]
Sorry, didn't mean to close the issue. I'll be making a `2.8` release that contains the change to the default error handling of `on_breach` callbacks.

**Comment by alisaifee** [comment]
Now available in [2.8.0](https://github.com/alisaifee/flask-limiter/releases/tag/2.8.0)

**Comment by alisaifee** [comment]
@afontenot please review the changes and if it satisfies your use cases, go ahead and close the issue.

**Comment by afontenot** [comment]
Can confirm, testing on 2.8.1, that the issue seems to be fixed in all the cases I've tested.
