### ISSUE TITLE
Egg fails to declare its dependencies on limits

### ISSUE THREAD

**Issue by ligthyear** [alisaifee/flask-limiter#37]
Heyah,

just tried your plugin, installed via `pip install` it failed because of the missing import of  `limits`. It appears that your setup.py/egg file doesn't declare this dependency right.

**Comment by alisaifee** [comment]
@ligthyear: thanks for the report. I've had a similar report earlier (#35) but couldn't reproduce it at all. I just tried installing `Flask-Limiter` (version : `0.8.2`) again - and limits `1.0.8` was correctly reeled in.

Could you please provide some details of your environment (maybe a log of the installation as well) so I could debug this further?

**Comment by alisaifee** [comment]
Fixed as per #38
