### ISSUE TITLE
TypeError: __init__() got multiple values for argument 'key_func'"

### ISSUE THREAD

**Issue by oxytis** [alisaifee/flask-limiter#384]
Something changed in limiter = Limiter(app, key_func=get_remote_address)

get_remote_address

Reverted to previous version to avoid error.

**Comment by alisaifee** [comment]
3.0 has a breaking change in the constructors arguments: https://flask-limiter.readthedocs.io/en/stable/changelog.html#v3-0-0

**Comment by alisaifee** [comment]
Closing as this is a documented breaking change and looks like the dependent repository already has a PR to address it.
