### ISSUE TITLE
getting 503 error .

### ISSUE THREAD

**Issue by mohittgupta** [alisaifee/flask-limiter#391]
I have implemented rate limits in my app, and everything is working fine. But if I cross my rate limits I get 429 error but if I continuously, trigger same API, I get the 503 error. Please help me with it.

**Comment by alisaifee** [comment]
Hi @mohittgupta, you'd need to provide some more details about how you're using the extension for me to help.

**Comment by mohittgupta** [comment]
initialized limiter as follows:

rate_limiter = Limiter(
    key_func=limit_key_func,
    headers_enabled=True,
    default_limits=['40 per second'],
    default_limits_cost=1,
    header_name_mapping={
        HEADERS.LIMIT: "X-My-Limit",
        HEADERS.RESET: "X-My-Reset",
        HEADERS.REMAINING: "X-My-Remaining",
        HEADERS.RETRY_AFTER: "Retry-After-Seconds"
    },
    storage_uri=redis_storage_uri(),
    storage_options=get_redis_storage_options(),
    strategy="moving-window",
    enabled=FLASK_LIMITER_ENABLED,
    # swallow_errors=True,
    # in_memory_fallback_enabled=True
)


and using it on every blueprint route as :
@rate_limiter.limit('10 per minute', cost=1)

**Comment by alisaifee** [comment]
Since you're using redis as a storage backend we can be sure that the 503 isn't originating from the request to redis. Just to make sure that connectivity to redis isn't the cause of the eventual 503 error, could you try using `swallow_errors=True` and see what happens?

**Comment by mohittgupta** [comment]
Tried this, but still getting 503 error after some 429 error.

**Comment by alisaifee** [comment]
Are you running your  application behind a proxy?
The extension itself never raises any http errors other than 429.

**Comment by mohittgupta** [comment]
Actually, nginx is giving this error.found it. Sorry to bother you.

**Comment by alisaifee** [comment]
> Actually, nginx is giving this error.found it. Sorry to bother you.

No worries, it really did sound like a downstream marking the application as unavailable due to repeated non 2xx responses.
