### ISSUE TITLE
`RATELIMIT_DEFAULT` application

### ISSUE THREAD

**Issue by Sija** [alisaifee/flask-limiter#392]
Hi there!

I wanted to clarify what exactly the `RATELIMIT_DEFAULT` setting does. At first I thought it's the default limit used for all _rate-limited_ routes. After noticing that some of the requests to our **not** rate-limited routes (only POST though 🤔) are subjected to the rate limits set in `RATELIMIT_DEFAULT`, I went back to check the docs, and I see that I possibly misread them at the first place:

> A comma (or some other delimiter) separated string that will be used to **apply a default limit on all routes**.

From the above it seems though, that this default is used for all of the routes, is that correct?
Also, any idea why only POST requests are subjected to it?

Best,
Siyâvash

**Comment by alisaifee** [comment]
default limits are applied to all routes that do not explicitly set their own limits.
So for example:

```
app = ....
limiter = Limiter(....., default_limits=["10/minute"])

@app.route("/one")
def one():
    ...

@app.route("/two")
@limiter.limit("1/minute")
def two():
   ...

@app.route("/three")
@limiter.limit("1/second", override_defaults=False)
def three():
   ...
```

In the above: `/one` will be limited as `10/minute`, `/two` will be limited as `1/minute` and the defaults will not be applied... and `/three` will be limited by both `1/second` and `10/minute` since it specifies `override_defaults=False`

**Comment by alisaifee** [comment]
> Also, any idea why only POST requests are subjected to it?

Sorry I missed this in my reply above. There is no reason why `POST` requests would be the only one subject to a limit unless it was explicitly specified in the `limit` decorator using the `methods` argument.

**Comment by alisaifee** [comment]
I've also made a minor tweak to the documentation to (hopefully) reduce the ambiguity [here](https://flask-limiter.readthedocs.io/en/latest/configuration.html#RATELIMIT_DEFAULT)

**Comment by alisaifee** [comment]
@Sija please close this if the clarification is sufficient

**Comment by Sija** [comment]
@alisaifee Sorry, had a super busy week. It's sufficient, thank you! 🙏

**Comment by Sija** [comment]
After I get back from the vacation, I'll try to reproduce the issue with selectively limiting `POST` requests and report findings, if any.
