### ISSUE TITLE
Question for documentation needed

### ISSUE THREAD

**Issue by Jakobovski** [alisaifee/flask-limiter#40]
1. Are multiple workers supported? For example running the application with gunicorn and 5 workers?

**Comment by alisaifee** [comment]
If you're using Redis or Memcached backends, there should be no issues with multiple workers - they'll all share the rate limit values.

However, if you're using the built in in-memory storage (which isn't  meant to be used in production anyways :smile:), then you have to be careful.

If the workers are all separate processes (for example starting an app with `gunicorn myapp:app -w 10` then the rate limiting will be on a per process basis). If the workers are threads (`gunicorn myapp:app --threads=10`) then the rate limiting will be shared by the threads.

Hope this answers your question.
