### ISSUE TITLE
[SUPPORT] Is there a way to save to a TXT file when the rate limit are exceeded?

### ISSUE THREAD

**Issue by sukhoi47** [alisaifee/flask-limiter#406]
First, thank you for developing and maintain this excellent library. It is very useful.

Some of my visitors are hitting the rate limit. For me it will be very relevant to see the time, IP the the resource (web page, etc.) the user tried to access each time the rate limit was triggered. Ideally that information will be saved in a TXT file.

I searched the flask-limiter documentation, but could only find some little reference to logging, that is not very clear for (a newbie like) me:
https://flask-limiter.readthedocs.io/en/stable/recipes.html#logging

As FYI, nowadays my web application has a logger implemented via [Loguru](https://pypi.org/project/loguru/) library.

Is there a way to record the user info that triggered the rate limit?

**Comment by alisaifee** [comment]
To implement a custom action whenever a rate limit is hit by a request, you can use the [on_breach](https://flask-limiter.readthedocs.io/en/stable/api.html#flask_limiter.Limiter.params.on_breach) callback. For example to log using `loguru` whenever a rate limit is hit you could do something like this:

```python
from flask import Flask, request
from loguru import logger

from flask_limiter import Limiter
from flask_limiter.util import get_remote_address


def log_using_loguru(breached_limit):
    logger.info(
        f"ratelimit {breached_limit.limit} exceeded at endpoint: {request.endpoint} for ip: {request.remote_addr}",
    )

def app():
    limiter = Limiter(
        get_remote_address,
        default_limits=["2/hour"],
        headers_enabled=True,
        storage_uri="memory://",
        on_breach=log_using_loguru
    )

    app = Flask(__name__)

    @app.route("/")
    def root():
        return "42"

    limiter.init_app(app)
    return app


if __name__ == "__main__":
    app().run()

```


Another approach is to use the recommendation from `loguru` itself in the README section about how to [intercept standard logging messages toward your Loguru sinks](https://github.com/Delgan/loguru#entirely-compatible-with-standard-logging):

```python
import logging
import sys

from flask import Flask
from loguru import logger

from flask_limiter import Limiter
from flask_limiter.util import get_remote_address

# Copied from loguru README
class InterceptHandler(logging.Handler):
    def emit(self, record):
        # Get corresponding Loguru level if it exists.
        try:
            level = logger.level(record.levelname).name
        except ValueError:
            level = record.levelno

        # Find caller from where originated the logged message.
        frame, depth = sys._getframe(6), 6
        while frame and frame.f_code.co_filename == logging.__file__:
            frame = frame.f_back
            depth += 1

        logger.opt(depth=depth, exception=record.exc_info).log(level, record.getMessage())


def app():
    limiter = Limiter(
        get_remote_address,
        default_limits=["2/hour"],
        headers_enabled=True,
        storage_uri="memory://",
    )

    app = Flask(__name__)

    @app.route("/")
    def root():
        return "42"

    limiter.init_app(app)
    # Configure loguru to intercept all logging done through std library logging library
    logging.basicConfig(handlers=[InterceptHandler()], level=0, force=True)
    return app


if __name__ == "__main__":
    app().run()

```

**Comment by sukhoi47** [comment]
@alisaifee 
Thank you for the fast answer.
With your information I could workout a solution that is in test and working perfectly.
