### ISSUE TITLE
Automatic IP Blocking in Flask Limiter

### ISSUE THREAD

**Issue by lunarmaniac** [alisaifee/flask-limiter#411]
I'm not sure if this feature already exists in Flask Limiter, and I'm unsure about its technical feasibility. However, my idea is that Flask Limiter could potentially enhance its functionality by automatically blocking requests from a specific IP address for a designated period of time after that IP address has triggered the rate limit by making too many requests. This could serve as a proactive measure against potential DDoS attacks.

Currently, when the rate limit is exceeded, users are redirected to a different web page. While this is useful, I think it would also be beneficial to introduce the ability for Flask Limiter to temporarily block incoming requests from that IP address after a certain number of requests have been made to the rate limit page. This could further safeguard the server from potential overload caused by continuous requests from the same IP address.

## Expected Behaviour

 
When a user's requests from a specific IP address consistently reach the rate limit and trigger the redirection to the limit reached page, my feature for Flask Limiter would keep track of these occurrences. After a certain threshold of requests to the limit reached page is reached, the system would identify this IP address as potentially engaging in malicious behavior or attempting a DDoS attack.

**Comment by alisaifee** [comment]
I think this could be a valuable feature to add.
The way I understand it - this would be sort of a `meta_limit` which enforces a "How many times in a period `X` can you breach a rate limit" and this `meta_limit` would be deducted from everytime a rate limit is hit in the application.

Contrived example:
```python
from flask import Flask
from flask_limiter import Limiter

app = Flask(__name__)
limiter = Limiter(..., default_limits=["10/minute"], meta_limits=["2/hour", "4/day"])

....
```

So in the above example, if a user breaches the `10/minute` twice in an hour, all subsequent requests will simply get a `429` for the remainder of the hour and this will get reset for the next hour. If the user breaches the `10/minute` twice again in the hour, they will get `429` for the remainder of the day.

Does this align with your proposal?

**Comment by alisaifee** [comment]
If you're interested I've pushed a first cut implementation of 'breach limits' (i.e. limits on how many times you can breach a rate limit in the application) [here](https://github.com/alisaifee/flask-limiter/commit/6686ba5a819cd5946fd2fdb9643ae6e2bd683901). The test case in that commit shows the expected behavior.

**Comment by lunarmaniac** [comment]
Sounds good.

**Comment by alisaifee** [comment]
Available in master now, and will be in the next release. For more details you can take a look at [this](https://flask-limiter.readthedocs.io/en/latest/recipes.html#meta-limits) recipe in the documentation.
