### ISSUE TITLE
Does GitHub re-release old versions?

### ISSUE THREAD

**Issue by tjni** [alisaifee/flask-limiter#416]
In [nixpkgs](https://github.com/NixOS/nixpkgs), we download this package's source from GitHub and validate it doesn't change by hashing it, but we notice that old versions seem to change when a new version is released (hence the hash changes and the build breaks):

```
diff -Naurd /tmp/y/flask-limiter/flask_limiter/_version.py /tmp/x/flask-limiter-3.3.1/flask_limiter/_version.py
--- /tmp/y/flask-limiter/flask_limiter/_version.py	2023-08-23 19:06:07.000000000 +0200
+++ /tmp/x/flask-limiter-3.3.1/flask_limiter/_version.py	2023-05-04 01:44:55.000000000 +0200
@@ -24,7 +24,7 @@
     # setup.py/versioneer.py will grep for the variable names, so they must
     # each be defined on a line of their own. _version.py will just call
     # get_keywords().
-    git_refnames = " (tag: 3.3.1, stable)"
+    git_refnames = " (tag: 3.3.1)"
     git_full = "b2f27ce0c7a12acc710254ab2d587cf106c01fc8"
     git_date = "2023-05-03 16:44:55 -0700"
     keywords = {"refnames": git_refnames, "full": git_full, "date": git_date}
```

The latest version released seems to embed the `stable` tag, but when a new version is released, the old one is changed. Is this happening on purpose or by accident?

**Comment by alisaifee** [comment]
I'm not at all familiar with nixpkgs so most of the following is based on some guess work:

The content of `_version.py` that you have shared in the snippet appears to be what it would look like if you created a source archive using `git archive 3.3.1` for example for the `3.3.1` tag (i.e. not the actual content checked into the source tree). This is because the versioning tool ([versioneer](https://github.com/python-versioneer/python-versioneer)) adds an expansion for the `_version.py` file to `git archive` [reference](https://github.com/alisaifee/flask-limiter/blob/master/.gitattributes#L2)

During the release process when a new release is published, I also update the `stable` branch - so it makes sense that the current tag would be at the same ref as `stable` and that on a subsequent release `stable` would be at a newer ref.

So if you made a source archive from an old tag once when it was the latest release and then again once there was a new release - the content of `git_refnames` would indeed change if you ran `git archive`.

**Comment by alisaifee** [comment]
Does [fetchFromGithub](https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/python-modules/flask-limiter/default.nix#L26) internally result in downloading the "Source code" tarball from the releases page [here](https://github.com/alisaifee/flask-limiter/releases)? If so, it looks like that file is regenerated using `git archive` on demand which means depending on when you request for the archive the `git_refnames` could definitely contain more or less refnames (i.e. at the point of release it would be `tag:..., master, stable` and later on just `tag:...`)

**Comment by tjni** [comment]
Thank you for responding and sending me on the right track! Your guess is right. It looks like this is a known issue upstream: https://github.com/python-versioneer/python-versioneer/issues/217.

There are a few options I have tried on the nixpkgs side:

1. Fetch from PyPI. This doesn't work for us, because we want to run tests, and the PyPI archive is missing some test files (such as pytest.ini and conftest.py).

2. Fetch the git repository instead of the GitHub source archive. This requires further changes in nixpkgs because that feature in nixpkgs only fetches shallow clones and versioneer does not have a strategy for that: https://github.com/python-versioneer/python-versioneer/issues/252.

If you are willing to help support our use case, I have a few ideas where we can work together:

1. Update all of the files needed to run tests to PyPI. Then, we can always fetch from there and leave a comment why.

2. Tweak the release process to commit something to `stable` prior to archiving so that the tagged version is never attached to the branch.

If this is too much work:

1. We can fetch the git repository directly and patch out the versioneer code used for getting the version. This is a bit ugly but is the only way because versioneer does not support overriding the version (https://github.com/python-versioneer/python-versioneer/issues/230).

**Comment by alisaifee** [comment]
I'm happy to try and make some changes to make this work better for nixpkgs!

The versioneer issue you linked has a good link that feels like the minimal change: https://github.com/c-pec/scli/commit/b08bfd497755cea7bb264612c0b6109d9795a20f

I'll give that a try and see if it makes the `git_refnames` stable.

**Comment by alisaifee** [comment]
Sorry, this would be the minimal change that I think could work: https://github.com/fsspec/gcsfs/pull/442/files

**Comment by tjni** [comment]
It might, that looks promising!

**Comment by alisaifee** [comment]
@tjni looks like it will work: [3.4.1](https://github.com/alisaifee/flask-limiter/releases/tag/3.4.1)

**Comment by tjni** [comment]
Thank you so much, I really appreciate your help. I will work on updating this in nixpkgs. I'll close the ticket as resolved 🎉

**Comment by alisaifee** [comment]
I'll port this patch to my other python packages since I assume they all have the same problem. (Flask-Limiter, depends on limits, which can optionally depend on coredis)
