### ISSUE TITLE
limiting 404?

### ISSUE THREAD

**Issue by hexkey** [alisaifee/flask-limiter#431]
Hello,

Please correct me if I am wrong, but it seems it's not possible to globally (whole app) limit 404 errors? I did try couple of options via @errors.app_errorhandler(404) and via @app.after_request + deduct_when=lambda response: response.status_code == 404, but no luck.

The problem I am seeing more on few flask apps is that bots are trying to bruteforce directory discovery, in process they create huge number of 404 errors, I would like to create a logic to limit number of 404 per ip. Can you help? Thank you.

**Comment by alisaifee** [comment]
Unfortunately the `404` handler runs internally in flask before the extension gets a chance to perform `before_request` checks so as far as I know this is not possible

**Comment by hexkey** [comment]
thank you for your response, was hoping that maybe I missed something. Thank you for making  and maintaining flask-limiter!
