### ISSUE TITLE
"Dictionary Size changed during iteration" around application deployment time

### ISSUE THREAD

**Issue by baydoun0** [alisaifee/flask-limiter#446]
## Expected Behaviour

Flask Limiter should behave gracefully during application initialization.

## Current Behaviour

About 50 times over the last couple of weeks, ever since we upgraded Flask Limiter to the latest version (we were on 1.x and now we're at 3.5.1), we consistently observe the following error on Sentry:

<img width="690" alt="Screenshot 2024-05-18 at 12 53 51 PM" src="https://github.com/alisaifee/flask-limiter/assets/113205876/24f6a9ec-e4f9-4a86-bf4a-22b28c49a9b4">

It happens around the time our application initializes after deployment.

<img width="317" alt="Screenshot 2024-05-18 at 12 54 20 PM" src="https://github.com/alisaifee/flask-limiter/assets/113205876/ea5ed0f2-e1e2-48f1-8dd3-4ea22684abd6">

## Steps to Reproduce

I don't have concrete steps to reproduce for everyone, our application is in production under normal load, and we service quite a bit of requests, but for us, steps to reproduce are simply:

1. Construct Blueprints with routes registered, some of which have rate-limiting (this doesn't actually matter, since we observe failures even on endpoints that DO NOT HAVE the limiter decorator)
2. Register all those blueprints to a Flask App instance.
3. Initialize Flask limiter as usual.

Concurrently, the application needs to be bombarded with requests.

## Your Environment

- Flask-limiter version: 3.5.1
- Flask version: 2.0.0
- Operating system: Amazon Linux 2
- Python version: 3.8

We're also using Redis as a backing store.

Note: We are constructing all blueprints and attaching all routes to them, and also configuring ALL `before_request` and `after_request` hooks _before_ initializing Flask Limiter in an attempt to mitigate this, but it's not working as expected. Flask Limiter seems to be kicking in immediately (which is fine, but it should handle the race condition better).

## Suggested Fix

The `self._blueprint_exemptions` field inside the `LimitManager` class is only modified in one place: the `add_blueprint_exemption` method. All that needs to be done is to add a lock, and acquire it when attempting to write, or iterate over `self._blueprint_exemptions`.

**Comment by alisaifee** [comment]
If the blueprints have all been constructed (and decorated with any `@exempt` decorators) before you call `limiter.init_app(app.....)` it's a bit unclear to me how the extension's `before_request` hook could be registered and thus be executed while the `add_blueprint_exemption` method is still being called.

**Comment by baydoun0** [comment]
We are not using the `exempt` decorator anywhere in our application, I double-checked. Only the `limit` decorator, and the `request_filter` decorator.

I can't actually figure out WHERE the calls to `add_blueprint_exemption` are happening, because it doesn't seem to be the case that this is called _anywhere_ other than from an `exempt` decorator call, which we are not doing.

YET, we see these errors in production.

**Comment by alisaifee** [comment]
Oh wow, I completely missed the `defaultdict` and this all makes sense now. Also, interesting that this hasn't been raised by anyone before! I'll work on a fix asap.

**Comment by alisaifee** [comment]
Fix will be available in [3.7.0](https://github.com/alisaifee/flask-limiter/releases/tag/3.7.0)

**Comment by baydoun0** [comment]
Awesome! Already bumped on our end and deploying to production as we speak -- fingers crossed

**Comment by alisaifee** [comment]
@baydoun0 please close the issue if/when you've verified that it no longer exists in your environment! Thank you.

**Comment by baydoun0** [comment]
I can confirm that this is no longer happening in production, so the bug is resolved! Thank you so much for fixing it this fast!
