### ISSUE TITLE
Use with blueprints in a separate file

### ISSUE THREAD

**Issue by tdeck** [alisaifee/flask-limiter#46]
I have seen [the documentation](https://flask-limiter.readthedocs.org/en/latest/#rate-limiting-all-routes-in-a-flask-blueprint) for flask-limiter with blueprints, but it seems to assume that the blueprint is defined inside the same file as the app object.

A common pattern with blueprints is to set up each blueprint in its own separate module, to create a module app. Then the main app module imports all the blueprints and registers them. In this case, there's no `app` object to use to construct the limiter. I can't import it (or the limiter) from the main module, as that will create a circular import. Is there a way to use per-route limits with a modular setup like this?

**Comment by alisaifee** [comment]
@tdeck, the limiter instance can be constructed without an `app` instance and later initialised using the `init_app` method.  

Does the following example match your description?
**directory structure**
```
.
└── example
    ├── __init__.py # empty file
    ├── app.py
    ├── bp1
    │   ├── __init__.py
    ├── core.py
```

**example/app.py**
```python
from flask import Flask

from bp1 import bp1
from example.core import limiter


def create_app():
    app = Flask(__name__)
    limiter.init_app(app)
    app.register_blueprint(bp1)

    @app.route("/nolimits")
    def nolimits():
        return "43"

    return app

if __name__ == "__main__":
    create_app().run()
```

**example/core.py**
```python
from flask.ext.limiter import Limiter

limiter = Limiter()
```

**example/bp1/__init__.py**
```python
from flask import Blueprint
from example.core import limiter

bp1 = Blueprint("bp1", __name__, url_prefix="/bp1")
limiter.limit("1/minute")(bp1)


@bp1.route("/")
def index():
    return "42"
```

**Comment by tdeck** [comment]
Ah thanks! I didn't realize you could construct the limiter without the app parameter and bind it later. That's exactly what I was looking for.
