### ISSUE TITLE
return in finally swallows exceptions

### ISSUE THREAD

**Issue by iritkatriel** [alisaifee/flask-limiter#460]
In https://github.com/alisaifee/flask-limiter/blob/812189d8bda77d54f537b9360c9bb32998eef22b/tests/test_context_manager.py#L19 there is a `return` statement in a `finally` block, which would swallow any in-flight exception.

This means that if an unhandled exception (including a `BaseException` such as `KeyboardInterrupt`) is raised from the `try` body, or any exception is raised from an `except:` clause, it will not propagate on as expected.

See also https://docs.python.org/3/tutorial/errors.html#defining-clean-up-actions.

**Comment by alisaifee** [comment]
@iritkatriel that is a test case and is intended to do that. Is there an actual problem you see there?

**Comment by iritkatriel** [comment]
```
        try:
            with limiter.limit("1/day"):
                resp += "maybe"
        except RateLimitExceeded:
            pass
        finally:
            return resp
```

The problem is that the above is equivalent to:

```
        try:
            with limiter.limit("1/day"):
                resp += "maybe"
        except:
            pass
        return resp
```

which is probably not what you intended. You intend to swallow `RateLimitExceeded` only, not all exceptions. That is best written as:

```
        try:
            with limiter.limit("1/day"):
                resp += "maybe"
        except RateLimitExceeded:
            pass
        return resp
```
