### ISSUE TITLE
Unable to disable limiter when running unittests

### ISSUE THREAD

**Issue by kiowa** [alisaifee/flask-limiter#50]
I am unable to disable the rate limiter while running my unit tests. 
Setting the `RATELIMIT_ENABLED = False` directly in config.py however works. But I'd like to do it programatically.

Considering my app setup is like this:

app.py:
```python
app = Flask(__name__)
app.config.from_object('config')
limiter = Limiter(app, global_limits=["500 per day", "100 per hour"])
```

tests.py:
```python
import app

def setUp(self):
    app.app.config['TESTING'] = True
    app.app.config['RATELIMIT_ENABLED'] = False
    bouncer.limiter.enabled = False
```

**Comment by kiowa** [comment]
After reading flasks documentation on Configuration Best Practices I'll refactor and fix this in my app instead.

**Comment by havok2063** [comment]
@kiowa How did you fix this?
