### ISSUE TITLE
User Specific Rate Limits

### ISSUE THREAD

**Issue by sokser** [alisaifee/flask-limiter#53]
I can't find any documentation on how to apply user specific rate limits. For example, my admins should have an unlimited rate limit, employees have a limit of 500/hour and verified users have 250/hour. How can we do something like this?

**Comment by authentik8** [comment]
One potential method would be to define your own decorator, and based on the incoming request, call the rate-limited function with the appropriate parameters. I've used this method to authorise requests to the same resource using either JWT or OAuth authorization headers.

Example code below:

```python
def rate_limited_resource():
    """
    Rate limit a resource depending on the user
    """
    def wrapper(f):
        admin_rate_limit = limiter.exempt()(f)  
        employee_rate_limit = limiter.limit("500 per hour")(f)
        verified_user_rate_limit = limiter.limit("250 per hour")(f)

        @wraps(f)
        def decorated(*args, **kwargs)
            user_type = get_user_type(request)

            if (user_type == 'admin'):
                return admin_rate_limit(*args, **kwargs)
            if (user_type == 'employee'):
                return employee_rate_limit(*args, **kwargs)
            if (user_type == 'verified_user'):
                return verified_user_rate_limit(*args, **kwargs)
        return decorated
    return wrapper
```

You would then use it by importing it and dropping a `@rate_limited_resource()` decorator over the views you want to protect.

Just my two ¢,

**Comment by lukas-gitl** [comment]
I'd be very interested in this as well... the above solution doesn't seem to work correctly (or I'm doing something wrong)

**Comment by alisaifee** [comment]
@sokser were you able to use dynamic limits for this and can this be closed?
