### ISSUE TITLE
Reset limit upon user log-in

### ISSUE THREAD

**Issue by Dean-Christian-Armada** [alisaifee/flask-limiter#57]
Is there a built-in function where it will reset the limit upon log-in?

Let's say I have a limit of 10.. May failed attempt is now 5 but on my 6th I logged-in and I want my limit remainings to reset to 0

**Comment by RobertDeRose** [comment]
You could do this on your own, there is now a `reset()` method for the limiter, but it was designed to reset all limits, but just a per key limit.

**Comment by alisaifee** [comment]
This could be better managed with the [deduct_when](https://flask-limiter.readthedocs.io/en/stable/api.html#flask_limiter.Limiter.limit.params.deduct_when) or [exempt_when](https://flask-limiter.readthedocs.io/en/stable/api.html#flask_limiter.Limiter.limit.params.exempt_when) arguments to control when you don't want to rate limit.

If that is still not enough, you could use the [current_limit](https://flask-limiter.readthedocs.io/en/latest/api.html#flask_limiter.Limiter.current_limit) or [current_limits](https://flask-limiter.readthedocs.io/en/latest/api.html#flask_limiter.Limiter.current_limits) attribute(s) to explicitly clear them, for example:

```python
app = Flask(__name__)
limiter_extension = Limiter(app)

@limiter_extension.limit("2/day")
@app.route("/login")
def login(....):
     # if login succeeded
     [limiter_extension.limiter.clear(limit.limit, *limit.request_args) for limit in  limiter_extension.current_limits]
```
