### ISSUE TITLE
In Memory Fallback, should use, or at least allow to use per route limits

### ISSUE THREAD

**Issue by RobertDeRose** [alisaifee/flask-limiter#59]
The current implementation does not allow for the In-Memory-Fallback to be enabled unless you provide a list of fallback rate limits.  I'm not sure I understand the design decision here, but it's fine if that fix the use case of most people.

However, I would like to know if I made a PR that would allow for In-Memory-Fallback that simply added a Memory Storage, but still used the per-route based limits, if you would be in favor or merging this?

The code change doesn't seem hard and I can do it in a backward compatible way but simply adding another configuration option to the Limiter constructor and the init code.

**Comment by RobertDeRose** [comment]
ping @alisaifee

**Comment by alisaifee** [comment]
Very sorry for the delay @RobertDeRose.

The original design did not account for inheriting rate limits when falling back to in memory as I was worried that if multiple application instances are sharing a single shared storage (memcache/redis), the meaning of something like `10/second` would change once the fallback is  activated. 

Having said that I agree that the flexibility to configure either way should be provided.

I've created a branch with a first cut implementation of how I understand what you've described. Please let me know if that is sufficient or if you'd like to contribute some changes.

**Comment by RobertDeRose** [comment]
@alisaifee Thanks, I was willing to do the work, but I appreciate it. I will test it out this week.

**Comment by alisaifee** [comment]
@RobertDeRose any updates on this implementation?

**Comment by RobertDeRose** [comment]
@alisaifee I'm very sorry, I haven't had the chance to try it out as we had to disable all rate limiting for the time being for other issues.  I really appreciate your time so I will try and make time to test this out as soon as I possibly can.

**Comment by anka-sirota** [comment]
@alisaifee is there something blocking this change from being merged?

Is this commit still have to be tested or does it have to be rebased on top of current stable first?

**Comment by RobertDeRose** [comment]
@anka-sirota I never got to test it, I moved off the project that was in need of it, and then I never got a chance to test it out.  I feel personally bad about that.

**Comment by anka-sirota** [comment]
> I never got to test it, I moved off the project that was in need of it, and then I never got a chance to test it out. I feel personally bad about that.

@RobertDeRose happens =] I've got a project that needs this functionality at the moment, and this change looks like it does the trick.

It appears to be working as expected, although I only tested with an unresolvable domain (got `[13:34:12][WARNING] flask-limiter extension.py:__check_request_limit:509 | Rate limit storage unreachable - falling back to in-memory storage`).

@alisaifee could you take a look at and possibly merge https://github.com/alisaifee/flask-limiter/pull/236?

**Comment by alisaifee** [comment]
Fixed by 1fa748e6b4d0345721b7aee72dbcbbdf1a27c0be
