### ISSUE TITLE
Retry-After header reporting some optimistic, and occasionally strange values

### ISSUE THREAD

**Issue by andymantell** [alisaifee/flask-limiter#62]
Hi,

I am having a slight issue with the Retry-After headers on my current project. If the user triggers too many requests to my rate limited endpoint, I am using the Retry-After header to wait for the right amount of time before letting their request through.

However, it almost seems that the header is a little "optimistic" timewise, because if I retry after that exact number of seconds, it triggers the rate limit again. However, on this request, the rate limiter actually says Retry-After _zero_ seconds. It says this several times in quick succession, before then saying Retry-After `-1484742195` seconds (exact value varies, but it's always large and negative).

I don't know whether I've misunderstood something, or if I'm doing something else daft, but I wondered how this value was calculated, and how reliable it was? If I arbitrarily add a few seconds to the Retry-After time it works fine, but I am reluctant to add a fixed value such as 5 seconds in case there are times when 5 seconds aren't enough. Adding 1 second doesn't seem to be sufficient, but adding 2 seconds seems to do the trick.

Once that Retry-After is up, what actually happens internally? Is it simply that I am observing the rate limit resetting itself and taking a non-zero amount of time to do so?

Thanks!

**Comment by alisaifee** [comment]
Thanks @andymantell - definitely sounds like a bug in the implementation. 
Could I ask you for some details about your setup (strategy, storage, rate limit string)

**Comment by andymantell** [comment]
Rate limit: `5/minute`
Strategy: Default - I assume fixed window?
Storage: In memory
`RATELIMIT_HEADERS_ENABLED: True`

We are using a custom key function to retrieve the user's IP address from a header as we are behind a proxy, but apart from that I think it's all fairly standard.

I'm snowed under for the next couple of days, but on Wednesday I should be able to put together a standalone test case to demonstrate the issue if that would be helpful?

Thanks,

Andy

**Comment by andymantell** [comment]
Hi @alisaifee,

Sorry for the delay. I've put a demo up here:

https://flask-limiter-issues-62.herokuapp.com/

This is the github repository for it:

https://github.com/andymantell/flask-limiter-issues-62

What you'll see is that I make a request once per second, to a route that is rate limited at 5/minute. Once the rate limit is triggered, it waits for the time specified in the `Retry-After` header before immediately trying to make the request again. What you should see is a little flurry of activity where the route says `Retry-After: 0`, before it finally allows it to go through again.

**Comment by alisaifee** [comment]
Thanks @andymantell - I can actually reproduce this with a unit test as well. Looks like the issue is that the `Retry-After` value tells you to retry after `n` seconds, but only when that `nth` second is complete will a new request be allowed in. I haven't worked out the details with the different strategies yet, but at first look it feels like just adding an extra second in the `Retry-After` value would actually solve the problem. What do you think?

**Comment by andymantell** [comment]
I _thought_ I had tried 1 second, and just adding 1 didn't seem to be enough. I will investigate a little more and double check if that's the case or not.

**Comment by andymantell** [comment]
1 second seems to be enough in my isolated test case, but on the actual project I'm working on it seems to not be enough. I will keep digging and see if I can get to the bottom of it...

**Comment by alisaifee** [comment]
@andymantell one point I forgot to mention is that the memory storage shouldn't really be used for any real application - its mostly for testing. Have you tried using memcache or redis storage?

**Comment by andymantell** [comment]
Ah interesting. It seems to perform well enough under load. Does the redis one use redis' expiration methods, instead of it being written in python? I wonder if that might also sort our issue...

I'll get it set up on the heroku demo and see if it sorts the issue. Maybe there is no bug and the only thing that needs to be "fixed" here is just some bigger words saying "Don't use this for production".

**Comment by andymantell** [comment]
I switched the heroku app to use redis this morning, but it still required me to add 1 second to the RetryAfter value. I guess it's just a rounding error or something?

Other than that it seems to be working, though I don't know whether it will work when I drop it into our main app, as that still needed more than 1 second adding.

To be honest, I'm not sure if there's a bug here or not. Shall I close it for the moment and reopen it at a later date if it is still an issue? I've popped a card on our backlog to move to Redis but it's not going to happen overnight.

**Comment by alisaifee** [comment]
I think I'll have to add the one second regardless of the storage backend as it does provide a safe guarantee.

Let's keep the issue open until we have a working solution for your application.

**Comment by andymantell** [comment]
HI @alisaifee,

We've switched our app to use Redis (finally!) instead of the in-memory storage, and it seems like we still need to add 1 second to the Retry-After time. So I guess if Flask-Limiter could add that second on instead of requiring applications to do that, that would be ace.

Thanks!

Andy

**Comment by alisaifee** [comment]
Wow, I'm sorry this issue has been open this long. I totally dropped the ball on this one. I'll get a `.1` out asap.

**Comment by andymantell** [comment]
Not at all - it's _us_ that has taken six months to get round to switching to Redis!

**Comment by andymantell** [comment]
Hi @alisaifee 

Just wanted to let you know that I updated my test case with the latest version from this repository and I can confirm that it definitely fixes the issue for me.

Thanks!

**Comment by alisaifee** [comment]
Awesome!
