### ISSUE TITLE
Rate limit per token

### ISSUE THREAD

**Issue by kharazi** [alisaifee/flask-limiter#64]
Is there any way for setting customized request limit for different user token? for example suppose for a specific endpoint like `/test` we have `1000 per day` limit for token A and `100000 per day` limit for token B.

**Comment by alisaifee** [comment]
Yes, you can do this by using the dynamically loaded rate limits. For example

```
def rate_limit_from_config():
    # fetch the limit based on the request token depending on how you store/configure it

@app.route("/test")
@limiter.limit(rate_limit_from_config)
def test():
    ...
```

**Comment by tuukkamustonen** [comment]
Just starting to use Flask-Limiter - would it be possible to pass the returned key from `key_func` into callable `limit_value`?

It's not necessarily needed, just thinking that it would be nice (to avoid always accessing `request.*` etc.)

**Comment by lukas-gitl** [comment]
Note that this doesn't seem to work when using a lambda function... since it checks for callable...
