### ISSUE TITLE
limits added to extension routes docs

### ISSUE THREAD

**Issue by illume** [alisaifee/flask-limiter#65]
Hello,

it wasn't clear to me how to add limits to extension routes in the documentation. Maybe this will help someone else...

# Using limits with Blueprints or flask extension routes
Perhaps you want to use limits on a flask extension?

Here is an example of adding limits to [flask-security-fork](https://pypi.python.org/pypi/Flask-Security-Fork) blueprint and views.
```python
    security = flask_security.Security(app, ...)

    # add to a particular view function.
    login = app.view_functions['security.login']
    limiter.limit("6/hour")(login)

    # add to a whole blueprint.
    limiter.limit("4/hour")(security.app.blueprints['security'])
```

**Comment by alisaifee** [comment]
Hi @illume would you be interested in writing up a small recipe in the documentation ?

**Comment by illume** [comment]
@alisaifee I updated the comment above... it should be able to go in the docs somewhere like that?

**Comment by alisaifee** [comment]
I'm going to skip on adding this to the documentation since this is really more about how each extension interacts with your app.

**Comment by illume** [comment]
Ok :)
