### ISSUE TITLE
Support key prefix to share storage instances between apps/envs

### ISSUE THREAD

**Issue by tuukkamustonen** [alisaifee/flask-limiter#66]
At the moment, Flask-Limiter creates keys like:

```
LIMITER/foo_client/admin_api.post_root_node/1/1/minute
```

To allow sharing same Redis instance with multiple apps, would be nice if Flask-Limiter supported something like:

```
Limiter(..., key_prefix='env_name')
```

That would generate keys like:

```
env_name:LIMITER/foo_client/admin_api.post_root_node/1/1/minute  # or
LIMITER/env_name/foo_client/admin_api.post_root_node/1/1/minute
```

I guess this feature would be beneficial for memcached users as well?

Note: Redis can run multiple "databases", but databases are not supported in Redis Cluster so it's not the safe way to go.

**Comment by alisaifee** [comment]
@tuukkamustonen could you please look at the linked pull request  - something like that?

**Comment by tuukkamustonen** [comment]
@alisaifee Yeah that's it. Can't comment on the technical implementation but that should do it 👍 .
