### ISSUE TITLE
Returning 429 for OPTIONS request

### ISSUE THREAD

**Issue by lukas-gitl** [alisaifee/flask-limiter#70]
Ideally OPTIONS requests just server static content and shouldn't be rate limited. This is a concern because Browser JavaScript can't handle those and only gets a `-1` back. 

So what is the best practise here? I'm assuming flask doesn't actually generate the response on an OPTIONS requests but just serves static?

Any one else got experience with this? How would I disable the limiter for OPTIONS requests?

**Comment by lukas-gitl** [comment]
For anyone looking on how to do this: there is a `methods` parameter on `.limit(...)`. OPTIONS requests shouldn't be very expensive (since they just return static information), so disabling the limiter for them should be fine.

**Comment by alisaifee** [comment]
Hi @lukas-gitl are you satisfied with that solution? 

I was considering maybe adding a global whitelist for the methods that rate limiting is enabled for (all by default), what do you think?

**Comment by lukas-gitl** [comment]
I would like an `exclude_methods` parameter on `.limit(...)` that I can just pass `OPTIONS` into. Rather than defining explicitly all methods I want to enable it for. Exposing the global white-list information (that already exists internally) would certainly be helpful as well.

**Comment by lukas-gitl** [comment]
@tkrajca That seems pretty simple. We'll see if we can use that instead! Thank you!

**Comment by lukas-gitl** [comment]
@tkrajca That seems pretty simple. We'll see if we can use that instead! Thank you!

@alisaifee Possibly put this into the documentation once I've confirmed?

**Comment by emanuellandell** [comment]
would be nice if we could also include the headers on OPTIONS so that user can see limits

**Comment by alisaifee** [comment]
There's a few different ways of handling this in the recent versions (`exempt_when`, `deduct_when` for example) and also the proposed solution in the thread.
