### ISSUE TITLE
Scope function docs seem to be wrong

### ISSUE THREAD

**Issue by kstrauser** [alisaifee/flask-limiter#72]
In the shared limit docs, the scoping function doesn't have an argument:

```python
def host_scope():
    return request.host
host_limit = limiter.shared_limit("100/hour", scope=host_scope)
```

When I tried writing my own function with that signature, I got an error:

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/flask_limiter/extension.py", line 383, in __check_request_limit
    limit_scope = lim.scope or endpoint
  File "/usr/local/lib/python2.7/site-packages/flask_limiter/extension.py", line 66, in scope
    return self._scope(request.endpoint) if callable(self._scope) else self._scope
TypeError: test_scope() takes no arguments (1 given)
```

The docs should be updated to say that scope functions have one argument: the request endpoint being called.

**Comment by alisaifee** [comment]
Thanks @kstrauser - I've fixed the documentation, though the usefulness of the parameter being the name of the request endpoint is dubious (I can't remember why I did that :P). For backward compatibility sake, I'll keep it as it is for now though until someone has a better idea.
