### ISSUE TITLE
unable to disable limiter during testing

### ISSUE THREAD

**Issue by havok2063** [alisaifee/flask-limiter#75]
How can we disable the rate limiter during our unit testing?  I cannot get it to work.  Setting `RATELIMIT_ENABLED = False` doesn't seem to work.   I'd like to globally turn off the entire limiter since I use the `limiter.limit()` in a lot of different locations, but don't want to add testing conditions everywhere.  Here is my app

```
def create_app(object_config=ProdConfig):
    app = Flask(__name__)
    app.config.from_object(object_config)
    ...
    limiter.init_app(app)
    for handler in app.logger.handlers:
        limiter.logger.addHandler(handler)

    return app    
```

and here is my testing app inside my pytest `conftest.py`

```
from myapp import create_app
import pytest

@pytest.fixture(scope='session')
def app():
    app = create_app(debug=True, local=True, object_config=TestConfig)
    return app
```
I load it with a Test Config which has `RATELIMIT_ENABLED` set to False but it does not work

```
class TestConfig(Config):
    TESTING = True
    DEBUG = True
    SQLALCHEMY_DATABASE_URI = 'sqlite://'
    BCRYPT_LOG_ROUNDS = 1  # For faster tests
    WTF_CSRF_ENABLED = False  # Allows form testing
    PRESERVE_CONTEXT_ON_EXCEPTION = False
    USE_PROFILER = False  # Turn off the Flask Profiler extension
    RATELIMIT_ENABLED = False  # Turn off the Flask Rate Limiter


```

**Comment by lukas-gitl** [comment]
```
limiter = Limiter(app)
limiter.enabled = True/False
```

**Comment by havok2063** [comment]
I tried that but it doesn't seem to be working.  Do you have any examples of turning off the limiter during for your testing suite but remains active for dev or prod runs?

**Comment by lukas-gitl** [comment]
We do it exactly as I posted and it works great for us:
(1) disable limiter if running tests or dev
(2) enable limiter if running qa/prod
(3) enable limiter if we want to use it in tests with `limiter.enabled`

Do you have a minimal test case where it doesn't work for you?

**Comment by havok2063** [comment]
Yeah, my test setup is more or less using the above code snippets.  I modified my pytest app fixture to the following

```
from myapp import create_app
from myapp.settings import TestConfig
from myapp.extensions import limiter
import pytest

@pytest.fixture(scope='session')
def app():
    app = create_app(debug=True, local=True, object_config=TestConfig)
    limiter.enabled = False
    return app 
```
Inside the create_app function is where the limiter becomes initialized with the app.  All routes for my api (in an api blueprint) get a limit set to 200/minute, which gets reached during the test suite.  All my web and api route tests utilize the app through a page fixture, which basically sets up a route object instance with convenience testing functions and such things.

```
@pytest.fixture()
def page(client, config, request, init_web):
    blue, endpoint = request.param
    page = Page(client, blue, endpoint)
    yield page
```

client and config are the standard pytest-flask fixtures.  My Page class is defined like 

```
@pytest.mark.usefixtures('app, get_templates')
class Page(object):
    ''' Object representing a Web Page '''
    def __init__(self, client, blue, endpoint):
        self.app = app()
        self.url = self.get_url(blue, endpoint)
        self.json = None
        self.data = None
        self.response = None
        self.client = client

    def get_url(self, blue, endpoint):
        return config.urlmap[blue][endpoint]['url']

    def load_page(self, reqtype, page, params=None):
        if reqtype == 'get':
            self.response = self.client.get(page, query_string=params)
        elif reqtype == 'post':
            self.response = self.client.post(page, data=params, content_type='application/x-www-form-urlencoded')
        self.load_data()

    def load_data(self):
        try:
            self.json = self.response.json
        except ValueError as e:
            self.json = None
        self.data = self.json['data'] if self.json and 'data' in self.json else ''

    def assert_webjson_success(self, expdata):
        self.assert200(message='response status should be 200 for ok')
        if isinstance(expdata, str):
            assert expdata in self.json['result']
        elif isinstance(expdata, dict):
            assert self.json['result']['status'] == 1
        elif isinstance(expdata, list):
            self.assertListIn(expdata, self.json['result'])
```

An example test is something like

```
@pytest.mark.parametrize('page', [('api', 'QueryView:index')], ids=['query'], indirect=True)
class TestQueryView(object):

    def test_get_query_success(self, page, params):
        page.load_page('get', page.url, params=params)
        data = 'this is a query'
        page.assert_success(data)
```

I think I'm using the test app fixture correctly but I'm not sure actually.   Let me know if this is helpful or if there's anything else I can provide.

**Comment by lukas-gitl** [comment]
Looks like your limiter is not initialised when you disable it? Where is the `limiter = Limiter(app, ...)`?

**Comment by havok2063** [comment]
I initialize all my extensions in a separate file called extensions.py.  In there I have 
```
from flask_limiter import Limiter
from flask_limiter.util import get_remote_address

# Route Rate Limiter
limiter = Limiter(key_func=get_remote_address)
```
Then wherever I need the limiter I just import it `from myapp.extensions import limiter`.    I've also tried moving the initialization to inside my `create_app` function, like so, 
```
def create_app(..):
    app = Flask(__name__)
    ...
    limiter = Limiter(key_func=get_remote_address)
    limiter.init_app(app)
    ...
    return app
```
but that also didn't work.    Can you provide a minimal test case of your test app, how you use it in your tests, and how you disable your limiter?  Are you using pytest or unittest?

**Comment by lukas-gitl** [comment]
We are using nose, but that shouldn't really make a difference. If you print out the limiter.enabled in the tests, does it reflect the correct enabled state?

I don't have a lot of time right now to get a minimal test case running. If you could provide something minimal that I could get work off of that would speed up things.

**Comment by havok2063** [comment]
I printed out the `limiter.enabled` state and does say it is turned off.  I think I found the issue where the settings for my development server (which is the one running) were overriding my test app settings and so the rate limiter was getting turned on.  I moved the disabled conditions into my dev settings, and it looks like it's now working.  I just ran a bunch of tests and the limiter never triggered.

**Comment by lukas-gitl** [comment]
Now I'm a little confused. Are you actually running a server? Best practise should be to use the flask test client `app.test_client(use_cookies=False)`.

**Comment by havok2063** [comment]
Yeah, we have kind of an odd setup and I haven't quite figured out how to adopt the best practices here.   Our software is a Flask web app with web/api routes, but is also a client-based Python package that provides tools that utilize the API.  The client-based version talks to the server-based version using the API.  Our testing directory contains tests for the web/api routes and the client-based tools.  Our direct tests on the api and web routes correctly utilize the flask test client, run and pass as you would expect.  However are tools tests currently need a local dev server running so their internal API calls have somewhere to go.  Plus they need the dictionary map of available routes on the server.  This is the messy part.  Ideally, I'd like all the tests to go through the flask test client.  I think I need to get what the server name and port address is the test client uses and set that up so the tools recognize that path.   I just haven't figured out how to grab that information from the test client, or how to apriori provide them with the app route map.

**Comment by lukas-gitl** [comment]
Urg. Yeah that sounds like you have some design flaws here. Ideal solution imo is:
(1) separate client and server code into two projects
(2) test server api using flask test client
(3) test client side framework using recording (I recommend vcrpy)

**Comment by alisaifee** [comment]
As there appears to be no further requirement from the extension itself, I am closing this issue.
