### ISSUE TITLE
Executing limiter key func twice per request

### ISSUE THREAD

**Issue by lily-mayfield** [alisaifee/flask-limiter#76]
I put a print statement in my limiter key function and I noticed that for every request it's accessed twice. Why is this done?

Also, I think this is the area of code that allows such to happen: https://github.com/alisaifee/flask-limiter/blob/master/flask_limiter/extension.py#L391-L392

**Comment by alisaifee** [comment]
Hi @lily-mayfield yeap you're right. Is your `key_func` not idempotent? I guess I hadn't considered that.
