### ISSUE TITLE
Unable to apply custom rate limit on get resource

### ISSUE THREAD

**Issue by djardine** [alisaifee/flask-limiter#81]
Hi, I haven't been able to get flask_limiter to work as expected in my particular use case. I'm using flask.blueprint to instantiate the routes, but I create classes for my routes that inherit from Resource and would like to apply rate limiting to the "get", "post", etc procedures that get called (as in the example below). What I'm finding is that the custom rate limits set in the decorator applied to the "get" function, in this case, are always ignored and the defaults are used. I've also tried the custom decorators that others have posted and they're also ignored. Is there a way to apply custom rate limiting in my use case that I'm missing? It seems like it's not possible to apply rate limit per the request type, but where would I apply the decorator such that it covers the entire endpoint?

Also per the other issue comments I've read, it was my expectation also that adding the "@limiter.limit()" decorator would not just set a custom limit but also trigger the "check()" action.

`class PropertyList(Resource):

    def __init__(self, permission_type = None):
        g.permission_type = permission_type
        self.parser = reqparse.RequestParser()
        self.parser.add_argument('access_token', type=str, required=True, help='No \'access_token\' provided')
        self.parser.add_argument('city_id', type=int, required=False, help='No \'city\' provided')
        self.parser.add_argument('region_id', type=int, required=False, help='No \'zipcode\' provided')
        self.parser.add_argument('room_types', type=str, action='append')
        self.parser.add_argument('property_types', type=str, action='append')
        self.context = self.parser.parse_args()

    @authentication
    @dblogging
    @market_limit     #shared_limit doesn't work
    @limiter.limit("10/minute")    #this gets ignored, defaults are still applied
    # @limiter.rate_limit()     # i tried some of the decorators listed in the issues comments here, but they didn't work in this case
    # @limit_and_check("10 per minute")     # i tried some of the decorators listed in the issues comments here, but they didn't work in this case
    def get(self):

        if not self.context.get('city_id') and not self.context.get('region_id'):
            return response_bad_request("Must provide 'city_id' or 'region_id' parameter")
        ....`

**Comment by djardine** [comment]
Just saw this blurb from the docs which puts me in the right direction, but now my question is, since my custom key_func depends on values set in the @authentication decorator, is there any way to manipulate the order in which the decorators are run?

`class MyView(flask.views.MethodView):
    decorators = [limiter.limit("10/second")]
    def get(self):
        return "get"`

**Comment by alisaifee** [comment]
@djardine sorry for the late response. The issue of ordering the rate limit has been resolved in the recent `1.0.0` release and you can find some more details about this in #67. Please do let me know if that satisfies your requirements.

**Comment by nicolaspanel** [comment]
@djardine @alisaifee : Same problem here, `@limiter.limit("...")` is ignored due to flask-restfull`s Ressource I guess.

Example:
```
@ns.route('', methods=['POST'])
class MyRessource(Resource):
    @limiter.limit('5000 per day;300 per hour;20 per minute') # always ignored, use default_limits instead
    def post(self):
        pass
```
@alisaifee : `_route_limits` is properly set [here](https://github.com/alisaifee/flask-limiter/blob/05ac59cd22262b2a9fa17ec90fe08befc880f77e/flask_limiter/extension.py#L535) but is ignored since both [`implicit_decorator`](https://github.com/alisaifee/flask-limiter/blob/05ac59cd22262b2a9fa17ec90fe08befc880f77e/flask_limiter/extension.py#L395)  and [`in_middleware`](https://github.com/alisaifee/flask-limiter/blob/05ac59cd22262b2a9fa17ec90fe08befc880f77e/flask_limiter/extension.py#L399) are false.

@djardine : Have you found a workaround ?

**Comment by SirNeuman** [comment]
I had the same issue with using '@limiter.limit('10/minute')`, but doing `@limiter.limit('1/6seconds')` seemed to work.

**Comment by lextiz** [comment]
@nicolaspanel Did you find any solution/workaround for your issue?

**Comment by nicolaspanel** [comment]
@lextiz 
I end up with a custom limiter:
```py
from functools import wraps
from flask import g, Blueprint, request
from flask_limiter import Limiter, RateLimitExceeded
from flask_limiter.util import get_ipaddr
from flask_limiter.wrappers import LimitGroup


class CustomLimiter(Limiter):
    """Override `flask_limiter.Limiter#limit` decorator since it does NOT support `flask.views.MethodView`
    required by flask-restful.

    An issue has been created here to describe the problem: https://github.com/alisaifee/flask-limiter/issues/81
    """
    def __init__(self):
        super().__init__(
            key_func=lambda: str(g.user.id) if hasattr(g, 'user') else get_ipaddr(),
            auto_check=False,
        )

    def _evaluate_limits(self, limits):
        failed_limit = None
        limit_for_header = None
        for lim in limits:
            limit_scope = request.endpoint
            limit_key = lim.key_func()
            assert limit_key, 'key expected'
            args = [limit_key, limit_scope]

            if self._key_prefix:
                args = [self._key_prefix] + args
            if not limit_for_header or lim.limit < limit_for_header[0]:
                limit_for_header = [lim.limit] + args
            if not self.limiter.hit(lim.limit, *args):
                self.logger.warning(
                    "ratelimit %s (%s) exceeded at endpoint: %s",
                    lim.limit, limit_key, limit_scope
                )
                failed_limit = lim
                limit_for_header = [lim.limit] + args
                break
        g.view_rate_limit = limit_for_header

        if failed_limit:
            raise RateLimitExceeded(failed_limit.limit)

    def limit(self, limit_value, key_func=None):
        def _inner(obj):
            assert not isinstance(obj, Blueprint)
            func = key_func or self._key_func

            if callable(limit_value):
                limits = [LimitGroup(limit_value, func, None, False, None, None, None)]
            else:
                limits = list(LimitGroup(limit_value, func, None, False, None, None, None))

            @wraps(obj)
            def __inner(*a, **k):
                self._evaluate_limits(limits)
                return obj(*a, **k)
            return __inner
        return _inner


limiter = CustomLimiter()
```

**Comment by lextiz** [comment]
@nicolaspanel Thanks a lot! @alisaifee Do you consider this as a bug? Shall I open a PR?

**Comment by lextiz** [comment]
Never mind, found the [docs](http://flask-limiter.readthedocs.io/en/stable/#using-flask-pluggable-views).

**Comment by X1Zeth2X** [comment]
For those who use class based and have other decorators (@) on their views `def get()` `def post()` e.t.c, the `decorators = [limiter.limit('5/minute')]` should be on top of those decorators for it to work.
I think this issue should be closed now.
