### ISSUE TITLE
RATELIMIT_KEY_PREFIX configuration constant not used

### ISSUE THREAD

**Issue by marblestation** [alisaifee/flask-limiter#88]
[Documentation](https://flask-limiter.readthedocs.io/en/stable/#configuration) indicates we can use the configuration constant "RATELIMIT_KEY_PREFIX" to establish a prefix but it does not seem to have any effect.

Looking at the code I see "RATELIMIT_KEY_PREFIX" is referred in the class C as "KEY_PREFIX" but it is never used anywhere. Alternatively, a prefix can be set via the key_prefix argument in the Limiter constructor. Not sure if the documentation is wrong, there is a bug in the code or I am misinterpreting something?

**Comment by alisaifee** [comment]
It's definitely a bug :)
