### ISSUE TITLE
Clarify what happens if default_limits option is not provided

### ISSUE THREAD

**Issue by danielstocks** [alisaifee/flask-limiter#95]
So the default value for `default_limits` to the Limiter() function is ´[]´. What does this mean though? That no rate limiting is applied for any routes? or is there some kind of built in default?

I guess a clarification in docs would be helpful, unless i missed something glaringly obvious.

**Comment by brunobell** [comment]
@danielstocks  `default_limits` to Limiter() is the default limits of all endpoints except for those exempted by default (mostly static files) and with `@limiter.exempt` decorator.

**Comment by alisaifee** [comment]
There is no default limit applied if you don't specify one. This means that if you enable the rate limiter and no default limits exist, it will essentially by a no-op

**Comment by danielstocks** [comment]
Thank you, I will open a PR to clarify this in docs.
