### ISSUE TITLE
Improvement: Allow lambda to be passed in for dynamic limit

### ISSUE THREAD

**Issue by lukas-gitl** [alisaifee/flask-limiter#96]
Currently we can only pass a function that is defined with `def`, a lambda function doesn't work.

The problem is that callable is checked.

**Comment by brunobell** [comment]
@lukas-gitl Actually we can pass a lambda function with args (checked lambda function), which returns a legal limit string(s). It's required to pass a limit string(s) to it anyway, isn't it?
I'm not quite sure if this is what you wanted but you may have a look at it and tell me your opinions.
```
from flask import Flask
from flask_limiter import Limiter

app = Flask(__name__)
limiter = Limiter(
    app,
)

lambda_limit_func = lambda x, y: '{} per {}'.format(x, y)


@app.route("/")
@limiter.limit(lambda_limit_func(1, 'hour'))
def slow():
    return "index"

if __name__ == '__main__':
    app.run(debug=True, port=5000)
```

**Comment by lukas-gitl** [comment]
You are passing a string... not a lambda function.

Below is a minimal outline of what the problem is:

**Doesn't work:**
```
lambda_limit_func = lambda: '10/5minutes'

@app.route("/")
@limiter.limit(lambda_limit_func)
def slow():
    return "index"
```

**Works:**
```
def regular_limit_func():
  return '10/5minutes'

@app.route("/")
@limiter.limit(regular_limit_func)
def slow():
    return "index"
```

**Comment by brunobell** [comment]
@lukas-gitl Actually, I have no problem running the script that you said did not work.
lambda is just any function in that it's callable, so there is NO PROBLEM with this:
```
from flask import Flask
from flask_limiter import Limiter

app = Flask(__name__)
limiter = Limiter(
    app,
)


lambda_limit_func = lambda: '10/5minutes'


@app.route("/")
@limiter.limit(lambda_limit_func)
def slow():
    return "index"


if __name__ == '__main__':
    app.run(debug=True, port=5000)
```
And the dynamic limit rule takes effect.  Maybe you should post your error message.

**Comment by lukas-gitl** [comment]
My bad. Had edited the env folder files and that screwed things up. Urg... always test in isolation. 

Apologies.... :/
