### ISSUE TITLE
Retry-After header always zero when using key prefix

### ISSUE THREAD

**Issue by andymantell** [alisaifee/flask-limiter#99]
The new key_prefix feature appears to cause the Retry-After header to be zero rather than having the value you would expect. Removing key_prefix from the attached test causes it to pass. As soon as you put key_prefix back again it then fails.

I have committed a failing test in https://github.com/alisaifee/flask-limiter/pull/98 but am not sure where to start looking with regards to fixing it.

Any ideas?

Cheers!

**Comment by alisaifee** [comment]
Thanks and apologies for this regression. Fixed in master.

**Comment by andymantell** [comment]
Thanks very much @alisaifee
